### ISSUE TITLE
[Landcover Toolkit] Replace "medioid" with more common "medoid"

### ISSUE THREAD

**Issue by gino-m** [google/earthengine-community#127]
Medoid appears to be much more common (153,000 search results) than medioid (4,220). Is there a reason to prefer "medioid"? @jdbcode was also asking about whether there's a reference for this.

**Comment by gino-m** [comment]
From @jdbcode in https://github.com/google/earthengine-community/pull/106#pullrequestreview-320272184:
> ...unless "medioid" is something different that "medoid", I suggest we change function/method names to "medoid" (seems to be the more common name) in a separate PR.

**Comment by gorelick-google** [comment]
+1

**Comment by gino-m** [comment]
> +1

Cool. Updated the description to rename this. Thanks!
