### ISSUE TITLE
[Community Tutorials] Creating a tutorial on developing web applications using Earth Engine

### ISSUE THREAD

**Issue by TC25** [google/earthengine-community#155]
I was planning to write a tutorial on developing and publishing apps on Earth Engine. I want to use my app (https://yceo.users.earthengine.app/view/uhimap) as an example template for the tutorial since I have used several ui functionalities there; plus it is easier than writing something from scratch. 

The main issues is that some of the datasets used in the app are not in the Earth Engine data catalog. However, since my method and results are published (https://www.sciencedirect.com/science/article/pii/S0303243418304653), I could make the data available. So, a couple of queries:

1. How would I go about making this dataset available in the catalog? I know of similar datasets like from the Global Forest Watch that are available. 

2. Do you think this tutorial is a good idea?

**Comment by TC25** [comment]
@gino-m Not sure how to assign people to issues.

**Comment by gino-m** [comment]
Hi TC, thanks for the proposal! We'll discuss this and get back to you soon. Assigning Tyler for now to keep it on our radar.

**Comment by gino-m** [comment]
Hi TC, thanks for your patience while we reviewed your proposal.

We think it's a great idea and we'd be happy to publish this in our Community Tutorials.

Regarding data sharing, can you set up the asset with public read access and refer to it in your tutorial?

Assigning back to you so for tracking. Thanks again for the proposal!

**Comment by TC25** [comment]
Sounds good. I will get to this soon.

**Comment by jdbcode** [comment]
Hi @TC25 I'm going to close this given the inactivity. Please reopen it in the future if you'd like to continue working on it.

Best regards.

**Comment by TC25** [comment]
Will do.
