### ISSUE TITLE
Issue with tutorials/identifying-first-day-no-snow/index.md

### ISSUE THREAD

**Issue by sgascoin** [google/earthengine-community#169]
Great tutorial!
- The Wang et al. citation in the reference section is probably not the right one 
- The tutorial suggests that the NDSI is equivalent to a snow fraction. It would be more precise to note that the snow fraction can be considered as a linear function of the NDSI (Salomonson, V. V., & Appel, I. (2004). Estimating fractional snow cover from MODIS using the normalized difference snow index. Remote sensing of environment, 89(3), 351-360).

**Comment by jdbcode** [comment]
Thanks for the feedback!

> The Wang et al. citation in the reference section is probably not the right one

Can you please suggest the right one.

> The tutorial suggests that the NDSI is equivalent to a snow fraction. It would be more precise to note that the snow fraction can be considered as a linear function of the NDSI (Salomonson, V. V., & Appel, I. (2004). Estimating fractional snow cover from MODIS using the normalized difference snow index. Remote sensing of environment, 89(3), 351-360).

The analysis is using MOD10A1.006 MODIS/Terra Snow Cover Daily L3 Global 500m SIN Grid, Version 6 from National Snow and Ice Data Center - "Snow cover is identified using the Normalized Difference Snow Index (NDSI)" - the dataset description is linked in the tutorial. Please edit the tutorial and make a pull request as you see fit to clarify it.

**Comment by sgascoin** [comment]
> Can you please suggest the right one.
I have no idea! But it surely isn't the one that is cited

**Comment by jdbcode** [comment]
> I have no idea! But it surely isn't the one that is cited

:) I see what you mean!
