### ISSUE TITLE
[Tutorial proposal] Monitoring change in forest vegetation condition

### ISSUE THREAD

**Issue by pskoulgi** [google/earthengine-community#184]
**What is the objective of the proposed tutorial?**
This tutorial will demonstrate an approach to assess forest vegetation condition using long term trends in vegetation status using MODIS data. It will walk through the choice of vegetation index and a particular season for computing annual composites, followed by trend analysis to compute trends in vegetation status change, a logic to infer vegetation condition, and visualize results. It will demonstrate calculating annual seasonal composites, reducers for trend analysis and area calculations, result charting and image visualizations. This is from a workshop I co-taught with a colleague at an [earth engine summit last year](https://sites.google.com/view/eeindia-advanced-summit/summit-resources#h.p_zAb7fDqX7uVW) 

**What is the scope of the proposed tutorial?**
Forestry

**Please provide an outline of the structure of the proposed tutorial?**
1. Import images, features
2. Compute annual summertime composites
3. Apply regression and infer vegetation condition
4. Visualize results: extent and direction of change

**In what format will you be submitting the tutorial?**
Markdown

Issue labels:
proposal, tutorial

**Comment by gino-m** [comment]
Hi @pskoulgi,

Thank you for submitting this clear, well-defined proposal. We think it would make an excellent addition to our Community Tutorials at https://developers.google.com/earth-engine/tutorials/community. 

Please proceed with instructions at https://developers.google.com/earth-engine/tutorials/community/write to create and submit your tutorial for review. I will then do a quick first editorial pass for form and structure. Once edits are received and comments are resolved, I will then assign a colleague to do a more thorough review. Please bear with us as we go through the review process, which can take a few iterations to complete.

If your tutorial seems much longer than typical tutorials found in our documentation, we may ask that you split it into two or more parts. For now, please feel free to submit the tutorial in its entirety and we can then discuss.

Looking forward to receiving your first pull request!

-Gino

**Comment by pskoulgi** [comment]
Hi @gino-m,

I put together a first draft and just sent a pull request. Let me know how it looks, when you get a chance. This is my first pull request, so excuse me if I didn't get something right -- happy to learn more and fix any mistakes.

One question on how to correctly use and reference vector data I have used here: where I needed some forest boundaries in the code, I have used one of my EE table assets which is imported from a shapefile that is published in a public repository. I have added pointers to that in the description of the table asset. Would that suffice or is it recommended that I do something more?

Looking forward to your review comments.
-Pradeep

**Comment by gino-m** [comment]
> One question on how to correctly use and reference vector data I have used here: where I needed some forest boundaries in the code, I have used one of my EE table assets which is imported from a shapefile that is published in a public repository. I have added pointers to that in the description of the table asset. Would that suffice or is it recommended that I do something more?

Good questions, sorry I just saw this now. Would it be possible to replace this asset with a few hard-coded polygons? This would allow the tutorial to be usable independently of your assets dir. Wdyt?

**Comment by pskoulgi** [comment]
I found that I can use the WDPA dataset instead. See [here](https://github.com/google/earthengine-community/pull/188/files/9ddf4d88738808a87c4d4ea40564fbeda91fd6da#r441306769).
