### ISSUE TITLE
Bug: lct.Landsat5() is not a function!!!

### ISSUE THREAD

**Issue by songyingxu** [google/earthengine-community#186]
```javascript
var lct =require('users/google/toolkits:landcover/api.js');
var roi = ee.FeatureCollection("users/wufvckshuo/HuangBoRiver");
Map.centerObject(roi,4);

var dataset = lct.Landsat5()
                  .filterDate('2009-04-01', '2009-09-30')
                  .filterBounds(roi)
                  .maskCloudsAndShadows();
Map.centerObject(roi);
Map.addLayer(roi);
```

Landsat8() is OK, but Landsat5() does not work!

![image](https://user-images.githubusercontent.com/32594744/83824807-06928a80-a70a-11ea-8ee2-33f533c53535.png)

**Comment by jdbcode** [comment]
The land cover tool kit is a work in progress. Limited parts of the library have been exposed as scripts available within the Earth Engine Code Editor for testing. As you've found, the `Landsat5` module is currently unavailable.

**Comment by songyingxu** [comment]
Thanks for your answer
