### ISSUE TITLE
[Tutorial proposal] Extracting Landsat values for plot points

### ISSUE THREAD

**Issue by swinsem** [google/earthengine-community#189]
**What is the objective of the proposed tutorial?**
This tutorial will go through code to extract Landsat reflectance values for points. We will use Landsat 5, 7 and 8 to get values for every overpass from 1984-present, and will use a focal mean for each point (each point will get the mean of 9 pixels including the center).

**What is the scope of the proposed tutorial?**
This process is very common in ecology and forestry, and is applicable anywhere on earth.

**Please provide an outline of the structure of the proposed tutorial?**
1. Context
   a. Why point extraction
   b. Why focal mean
   c. Recognition that the mean reflectance of 90m x 90m is pretty large for some purposes, but recent work could use the same general methods with Sentinel 2 or another satellite for a focal mean with 30m resolution if you only need recent values.
   d. Suggestions of things to do with this data, including calculating NDVI and getting the max NDVI (Note: This could pretty easily be added to the tutorial and is almost certainly the most common use of these data, but I think it may make the structure a little confusing)
2. Import points (will supply with some random example points)
3. Prepare functions for Landsat preparation
   a. Cloud masks and renaming bands for both OLI and TM/ETM+
   b. Load L5, L7, and L8 image collections using the masks and band names
4. Reduce region to get values surrounding each point
   a. For each image, find each point and do a region reduction (mean in this tutorial)
   b. Add metadata for the satellite and date along with the reflectance values
   c. Flatten the collection of collections to get a single featureCollection with one row for each unique image-point combination
5. Export
   a. Export to Asset
   b. Export to Drive
6. References

**In what format will you be submitting the tutorial?**
Select one: **[Markdown]**(https://guides.github.com/features/mastering-markdown/) 

This request will be reviewed by the Earth Engine community maintainers, who will reply on this issue tracker with any questions or suggestions. Once approved, this issue will be assigned to you and you can begin work on the tutorial following instructions in [Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write). When ready, enter “Closes #issueno” in the description of your Pull Request to link the tutorial to this issue.

Issue labels:
proposal, tutorial

**Comment by gino-m** [comment]
Hi @swinsem, your community tutorial proposal has been accepted. To get
started writing a new tutorial, please follow [these instructions](https://developers.google.com/earth-engine/tutorials/community/write). Please be sure to take @jdbcode 's suggestions into consideration and/or discuss them here with him before beginning. We look forward to receiving your contributions!

**Comment by swinsem** [comment]
Thanks! Could I switch from Markdown to Colab?

**Comment by jdbcode** [comment]
Definitely!

**Comment by jdbcode** [comment]
Hi @swinsem, just checking in, please let me know if I can help move this tutorial along in any way. Note that I recently published an EE Python API Colab Notebook [tutorial](https://colab.sandbox.google.com/github/google/earthengine-community/blob/master/tutorials/time-series-visualization-with-altair/tutorial.ipynb) that you might find useful for examples of formatting conventions, etc.

Best,
Justin

**Comment by swinsem** [comment]
Hey @jdbcode sorry for the delays! I've been working on some other pressing research things but will try to get this finished up by the end of September. I'm leaving on vacation tomorrow so won't be able to work on it for a little while.  

I was considering adding in a way to do weighted average, for example with the center pixel counting for twice the surrounding pixels. In looking for citations for the Context section, I found there's quite a bit of variation in how people use neighborhood averages even within the fire severity mapping literature I was reading, so I thought it would be cool to include this as another common method and extension of the simple average. Would I do this using splitWeights?

**Comment by jdbcode** [comment]
@swinsem The tutorial is published! 🎉 🥇 

https://developers.google.com/earth-engine/tutorials/community/extract-raster-values-for-points

It was great working with you and thanks for your perseverance on this!

**Comment by jdbcode** [comment]
Closed by #243

**Comment by jdbcode** [comment]
Closed by #243
