### ISSUE TITLE
[Tutorial proposal] Rapid Classification of croplands: Case Study of smallholder maize cultivated lands

### ISSUE THREAD

**Issue by PJNation** [google/earthengine-community#191]
**What is the objective of the proposed tutorial?**
The objective of this tutorial is to guide institutional and individual users to implement an automated routine/tool (in GEE) for classification of croplands within Nigeria's farming system, based on contextual peculiarities related to season and cropping practices. This tutorial is focused on developing the basic competency of the prospective user(s) to ingest ground-truth data and generate quick outputs about the regional estimate of land area sown with Maize. 

**What is the scope of the proposed tutorial?**
Landcover classification for croplands

**Please provide an outline of the structure of the proposed tutorial?**
1. Introduction
  a. Need to classify croplands
  b. Value for users
  c. Data Sources
2. Data preparation and checking
a. Groundtruth reference
b. Importing boundary files
c.  Sentinel 2A Imageries

3. Analytics 
a. Defining model
b. Selecting/optimizing Classifiers
c. Generating results

4. Plotting the charts to generate insights

5. Exporting Outputs

**In what format will you be submitting the tutorial?**
Select one: [Markdown](https://guides.github.com/features/mastering-markdown/) 

This request will be reviewed by the Earth Engine community maintainers, who will reply on this issue tracker with any questions or suggestions. Once approved, this issue will be assigned to you and you can begin work on the tutorial following instructions in [Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write). When ready, enter “Closes #issueno” in the description of your Pull Request to link the tutorial to this issue.

Issue labels:
proposal, tutorial

**Comment by PJNation** [comment]
Hi Tyler (@tylere): Is there any chance to get this tutorial proposal reviewed and approved this week pls?

**Comment by gino-m** [comment]
Hi @PJNation , your community tutorial proposal has been accepted! To get
started writing a new tutorial, please follow
[these instructions](https://developers.google.com/earth-engine/tutorials/community/write).
Looking forward to receiving your contributions!
