### ISSUE TITLE
[Tutorial proposal] Getting Started With The Earth Engine App Creator

### ISSUE THREAD

**Issue by mibrah42** [google/earthengine-community#209]
**What is the objective of the proposed tutorial?**
This tutorial is an introduction to the Earth Engine App Creator (https://ee-app-creator.appspot.com/), an open source tool that allows developers to build rich Earth Engine applications. The tutorial will walk through building a sample app using the tool and converting into a functional UI on the code editor.

**What is the scope of the proposed tutorial?**
The tutorial covers the basic usage of the app creator, including a walk through of its features, and runs through multiple examples of building an Earth Engine App.

**Please provide an outline of the structure of the proposed tutorial?**
1. **Introduction**
  **_a. What is the Earth Engine App Creator?_**
  **_b. Purpose_**
2. **Getting Started Guide**
  **_a. Templates_**
          i.     Structure
          ii.    Selecting a template
          iii.   Changing templates
          iv.   Duplicating templates
          v.    Importing templates
          vi.   Exporting templates
          vii.  Mobile templates
  **_b. Widgets_**
          i.    Types
          ii.   Adding widgets
          iii.  Removing widgets
          iv.  Editing widgets
          v.   Sharing widgets
  **_d. Palettes_**
          i.    Changing color palette
  **_e. Code Editor_**
          i.    Importing template
          ii.   Widget interface
          iii.  Binding callbacks
          iv.  Creating responsive apps
          v.   Creating multi-themed apps
          vi.  Creating multi-lingual apps
          vii. Creating multi-functional apps

**In what format will you be submitting the tutorial?**
Markdown

This request will be reviewed by the Earth Engine community maintainers, who will reply on this issue tracker with any questions or suggestions. Once approved, this issue will be assigned to you and you can begin work on the tutorial following instructions in [Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write). When ready, enter “Closes #issueno” in the description of your Pull Request to link the tutorial to this issue.

Issue labels:
proposal, tutorial

**Comment by jdbcode** [comment]
This will be a valuable contribution for getting users started quickly on building EE Apps - thanks for doing this! 
Let us know if we can help in any way.
Assigning back to you so for tracking.

**Comment by jdbcode** [comment]
@mibrah42 I'm going to close this given the inactivity. Please reopen it in the future if you'd like to continue working on it.

Best regards.
