### ISSUE TITLE
[Tutorial proposal] Detecting Changes in Sentinel-1 Imagery

### ISSUE THREAD

**Issue by mortcanty** [google/earthengine-community#210]
**What is the objective of the proposed tutorial?**
The Sentinel-1 missions of the ESA provide a fantastic source of free, weather-independent Earth observation data with revisit times of the order of 6-12 days. The Google Earth Engine team monitor and ingest the imagery data  as fast as they are produced, thus removing the burden from the user of searching, pre-processing and georeferencing. In this tutorial we will analyze Sentinel-1 imagery archived on the GEE in order to detect statistically significant changes over time. As the adverb "statistically" hints, we will need a basic understanding of the statistical properties of SAR imagery in order to proceed, and the adjective "significant" implies that we  learn the fundamentals of hypothesis testing.

**What is the scope of the proposed tutorial?**
Specifically, we will be analyzing the dual polarimetric intensity images in the GEE archive and developing, step-by-step, methods to detect changes, both in bitemporal as well as multitemporal imagery. The JavaScript and Python API's to the GEE can be easily programmed to analyze time series of Sentinel-1 acquisitions virtually anywhere on the globe. Detected changes, both short- and long-term can be related to landscape dynamics and human activity, and examples will be given.

**Please provide an outline of the structure of the proposed tutorial?**
 I would suggest dividing the tutorial into three parts, each submitted as a separate pull request :
-  Single and multi-look image statistics
-  Hypothesis testing for change detection
-  Applications

**In what format will you be submitting the tutorial?**
 [Colab](https://research.google.com/colaboratory/faq.html)

This request will be reviewed by the Earth Engine community maintainers, who will reply on this issue tracker with any questions or suggestions. Once approved, this issue will be assigned to you and you can begin work on the tutorial following instructions in [Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write). When ready, enter “Closes #issueno” in the description of your Pull Request to link the tutorial to this issue.

Issue labels:
proposal, tutorial

**Comment by jdbcode** [comment]
Hi @mortcanty, we're pleased to accept your tutorial proposal. We're particularly excited about the topic, as we have very few SAR examples.

Please see this [Colab notebook template](https://colab.sandbox.google.com/github/google/earthengine-community/blob/master/tutorials/tutorial-template.ipynb) for instructions on setting up the notebook to comply with our publishing flow (license, author, GitHub repo directory and file naming conventions).

Note that it is best if tutorials rely on datasets/assets from the Earth Engine Catalog or those that can be computed (i.e. avoid using shared private assets whenever possible). 

Comment on this issue if you have any questions.

We look forward to seeing the tutorial!

**Comment by mortcanty** [comment]
Thanks for the acceptance. It is apparently not possible to use ipyleaflet in colab, although it runs fine in Jupyter notebooks. Is this likely to be a permanent disadvantage of colab?

**Comment by tylere** [comment]
Colab has a different security model for cell outputs, so Jupyter widgets don't work without significant modifications. Many of the basic widgets have been ported, but not advanced widgets like ipyleaflet. Relevant issues:
https://github.com/googlecolab/colabtools/issues/60
https://github.com/jupyter-widgets/ipyleaflet/issues/195

**Comment by mortcanty** [comment]
Bit of a shame re interactivity. But I can live with it.

Tyler Erickson <notifications@github.com> schrieb am Mi., 19. Aug. 2020,
16:17:

**Comment by mortcanty** [comment]
Sorry, I see that I can import and use folium. Great!

**Comment by tylere** [comment]
Yes, examples of using folium to display Earth Engine results are shown in the example Colab notebooks on the [Python Install](https://developers.google.com/earth-engine/guides/python_install#install-options) page and the [Time Series Visualization with Altair](https://developers.google.com/earth-engine/tutorials/community/time-series-visualization-with-altair) tutorial.

**Comment by mortcanty** [comment]
@googlebot I signed it!

**Comment by mortcanty** [comment]
Here is a preview link to Part 1

https://colab.research.google.com/drive/19AMuogpipsMDo8Rd8i0IBu6jASVTKQye?usp=sharing

**Comment by clausmichele** [comment]
Thanks a lot for the first two parts of this tutorial, I really look forward to read the 3rd part about multitemporal filtering!

**Comment by jdbcode** [comment]
@clausmichele - Thanks for your interest in @mortcanty's tutorials! They are certainly a great benefit to the GEE and SAR community!

Mort's third tutorial is in review (#245) and will probably be published within a week or two. I'll post the page here when it is ready.
