### ISSUE TITLE
DEM SPATIAL ANALYSIS

### ISSUE THREAD

**Issue by morandiaye** [google/earthengine-community#212]
**What is the objective of the proposed tutorial?**
This tutorial attempt to explain the geospatial analysis we can make with Digital Elevation Model in Google Earth Engine. 

**What is the scope of the proposed tutorial?**
The scope is of this tutorial is geoscience particulary hydrology.

**Please provide an outline of the structure of the proposed tutorial?**
1. Import Collection image
2. Outline Podor limit
3. Clip Data with Podor limit
4. Geoprocessing 

**In what format will you be submitting the tutorial?**
Select one: [Markdown](https://guides.github.com/features/mastering-markdown/) 

This request will be reviewed by the Earth Engine community maintainers, who will reply on this issue tracker with any questions or suggestions. Once approved, this issue will be assigned to you and you can begin work on the tutorial following instructions in [Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write). When ready, enter “Closes #issueno” in the description of your Pull Request to link t

[DEM_Geoprocessing-master.zip](https://github.com/google/earthengine-community/files/5114691/DEM_Geoprocessing-master.zip)

he tutorial to this issue.

Issue labels:
proposal, tutorial

**Comment by morandiaye** [comment]
Tutorial to analyse DEM : SRTM

**Comment by jdbcode** [comment]
Hi @morandiaye - thanks for initiating this conversation about your idea for a tutorial!

Can you please provide a little more detail on what is to be included in the "Geoprocesing" section. Our intention with these tutorials is to provide users with material that is not covered in the Earth Engine Developer Guide and/or provides an applied workflow or example for using Earth Engine to answer a practical question. I think that a section that describes the `ee.Terrain` module would be useful, but should also include a brief example of using the results (e.g. slope, aspect, hillshade) to answer a question. For instance, how might you color code high angle slopes that are considered vulnerable to erosion during heavy rain events - these could be given protection from logging, farming, etc or remediated if soil/vegetation was recently disturbed.

I look forward to learning more about your ideas!

Best,

Justin

**Comment by morandiaye** [comment]
Hi @jdbcode 
You are right in geoprocessing I deal with aspect hillshade and slope and that is ready describe in ee.terrain documentation. I will get back to you soon and bring some ideas how to use DEM processing to improve sustainable land management.  
Thank for this feedback. I really appreciate

**Comment by jdbcode** [comment]
@morandiaye I'm going to close this given the inactivity. Please reopen it in the future if you'd like to continue working on it.

Best regards.
