### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by christelle-xu** [google/earthengine-community#215]
The [Rapid Classification of Croplands tutorial](https://developers.google.com/earth-engine/tutorials/community/classify-maizeland-ng) seems to be missing from the master branch:

- a shapefile layer labeled 'aoi'
- a csv: training-pts
- a csv: validation-pts

Incidentally, I was able to find version of training-pts.csv and validation-pts.csv on old branches but not 'aoi'. These files should be located here: 'projects/earthengine-community/tutorials/classify-maizeland-ng/'.

**Comment by jdbcode** [comment]
Thanks - we are working on it. Please see the thread starting here: https://github.com/google/earthengine-community/pull/192#issuecomment-674945302

In the meantime you can access and export the assets:

```
var aoi = ee.FeatureCollection('projects/earthengine-community/tutorials/classify-maizeland-ng/aoi');
var trainingPts = ee.FeatureCollection('projects/earthengine-community/tutorials/classify-maizeland-ng/training-pts');
var validationPts = ee.FeatureCollection('projects/earthengine-community/tutorials/classify-maizeland-ng/validation-pts');
```

Assigning to @PJNation

**Comment by christelle-xu** [comment]
I seem to have misread that thread initially. Thank you for the references, I will take a look.
