### ISSUE TITLE
Issue with tutorials/modis-ndvi-time-series-animation/index.md

### ISSUE THREAD

**Issue by bywaters** [google/earthengine-community#241]
When I change spatial extend of polygon the video is blank

**Comment by jdbcode** [comment]
Can you please share the script that produces the error. It will help me identify the problem. Thank you.

**Comment by bywaters** [comment]
I resolved it.
Thanks!
Sharon

**Comment by jdbcode** [comment]
Glad to hear it!

**Comment by NomitRwt** [comment]
Was trying to do the same thing from the [tutorial](https://github.com/google/earthengine-community/blob/master/tutorials/modis-ndvi-time-series-animation/modis-ndvi-time-series-animation.js) I only modified the variables `var mask` and `var region`. The script is [here](https://code.earthengine.google.com/?accept_repo=users/nomitrwt/test).

**Comment by bywaters** [comment]
Great, thanks so much

**Comment by jdbcode** [comment]
Hello @bywaters. Please update you script so that the `mask` variable is defined as such:

```js
var mask = ee.FeatureCollection('USDOS/LSIB_SIMPLE/2017')
  .filter(ee.Filter.eq('country_na', 'India'));
```

The problem is that the 'USDOS/LSIB_SIMPLE/2017' feature collection property 'wld_rgn' has no entry for 'India'; you must use the 'country_na' property instead.
