### ISSUE TITLE
[Tutorial proposal] Introduction to the Google Earth Engine Python API: data catalog exploration, static and interactive mapping

### ISSUE THREAD

**Issue by guiattard** [google/earthengine-community#248]
**What is the objective of the proposed tutorial?**
In this tutorial, an introduction to the GEE Python API is presented. After some setups and some exploration of the Earth Engine Data Catalog, we’ll see how to handle geospatial datasets with pandas and make some plots with matplotlib. Particularly, we’ll see how to get the timeseries of a variable on a region of interest. 

**What is the scope of the proposed tutorial?**
An application of different principals will be illustrated to extract and compare Land Surface Temperature in an urban and a rural area near the city of Lyon (France) to illustrate the heat island effect of urban areas.

**Please provide an outline of the structure of the proposed tutorial?**
1. Introduction
2. Exploration of the Earth Engine Data Catalog
3. Installation of the earth-engine-api and start
    3.1 Some setups
    3.2 Start to play with collections
    3.3. Get some time series
4.Static mapping of Land Surface Temperature and Ground Elevation
    4.1. Get a static map
    4.2. Clip an image on a region of interest
    4.3. Export a geotiff file
5.Interactive mapping using folium

**In what format will you be submitting the tutorial?**
[Colab]

**Others**
I plan to adapt the current version of the tutorial I made regarding your guidelines: https://guillaumeattard.com/introduction-to-the-google-earth-engine-python-api-data-catalog-exploration-static-and-interactive-mapping/

I made this tutorial for my students.

This request will be reviewed by the Earth Engine community maintainers, who will reply on this issue tracker with any questions or suggestions. Once approved, this issue will be assigned to you and you can begin work on the tutorial following instructions in [Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write). When ready, enter “Closes #issueno” in the description of your Pull Request to link the tutorial to this issue.

Issue labels:
proposal, tutorial

**Comment by jdbcode** [comment]
Hi @guiattard, your community tutorial proposal has been accepted. To get started writing a new tutorial, please follow [these instructions](https://developers.google.com/earth-engine/tutorials/community/write#colab-notebook).

One initial note: you might add a method to draw EE tiles to the Folium map, similar to the one [here](https://colab.sandbox.google.com/github/google/earthengine-api/blob/master/python/examples/ipynb/ee-api-colab-setup.ipynb#scrollTo=Ljo5dbLkfmVm) - add params as needed.

We look forward to receiving your contributions!

**Comment by guiattard** [comment]
Hi, Thank your for your positive response. Two issues arise when I ask a pull resquest:
- "absolute src paths not allowed: src=\"https:/": should I remove all urls links from my notebook ?! 
- "first cell must contain valid copyright header": strange because I am using your colab template.

Thank you for your help.

**Comment by jdbcode** [comment]
Hi @guiattard, I'll comment on these issues in PR #254. I'll be offline Nov. 23-25, so won't start reviewing until the first week in Dec. – thanks for your patience.

**Comment by jdbcode** [comment]
The tutorial has been merged and published.
