### ISSUE TITLE
Issue with tutorials/classify-maizeland-ng/index.md

### ISSUE THREAD

**Issue by flppgg** [google/earthengine-community#255]
Issue Description:

when I try run the code, I get this error:

"Training points: Layer error: Collection.loadTable: Collection asset 'projects/earthengine-community/tutorials/classify-maizeland-ng/training-pts' not found."

**Comment by jdbcode** [comment]
Thank you for bringing this to our attention. The asset permission settings have been adjusted - you should have access now.
