### ISSUE TITLE
drought monitoring using tci,vci,evi with google earth engine

### ISSUE THREAD

**Issue by kyawsanrs** [google/earthengine-community#258]
Description

Technical Level
beginner | intermediate | advanced

Length
short (< 250 words) | medium (250-500 words) | long (1000 words )

**Comment by jdbcode** [comment]
Hi @kyawsanrs - are you interested in submitting an Earth Engine tutorial? If so, please see this section on [proposing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write#proposing_a_tutorial); use the blue button at the end of the section to access a [proposal template](https://github.com/google/earthengine-community/issues/new?assignees=gino-m%2C+tylere&labels=tutorial+proposal&template=propose-a-tutorial.md&title=%5BTutorial+proposal%5D+Your+tutorial+title+here).

Best,
Justin

**Comment by jdbcode** [comment]
@kyawsanrs I'm going to close this given the inactivity. Please submit a new issue if you'd like to propose a tutorial in the future.

Best regards.
