### ISSUE TITLE
Issue with tutorials/forest-cover-loss-estimation/index.md

### ISSUE THREAD

**Issue by gifford27** [google/earthengine-community#262]
Hello! I am very thankful for this code as this hugely help me accomplish the majority of my work. All of the layers that were reprojected to the nominal scale in order to minimize the effect of changing the resolution resulted in an error where it says "Tile error: Object too large (129662248 bytes)".

Hopefully, this will be solved.

Thank you very much for sharing this script.

**Comment by gino-m** [comment]
HI @gifford27, sorry for the extremely delayed response, we haven't been regularly monitoring this channel. The tutorial runs every night and produces valid results. Closing for now as not reproducible.
