### ISSUE TITLE
Sentinel5P: Incomplete Images.

### ISSUE THREAD

**Issue by Mohammadreza20** [google/earthengine-community#267]
Hello
I have a serious problem with GEE data.
When I run my code for this date (`["2019/12/31,2020/01/01"]`) and get a mean of all images, I got this result:

  ```JS
      // Cloud mask for pixels with less than 5% cloud cover
        var cloudMask = function(image) {
              return image.updateMask(image.select("cloud_fraction").lt(0.4));
            };
        var NO2 = ee.ImageCollection('COPERNICUS/S5P/OFFL/L3_NO2')
                        .select('tropospheric_NO2_column_number_density')
                        .filterDate('2019-12-31', '2020-01-01')
                        .filterBounds(Area)
                        //.map(cloudMask)
        
        var meanNO2 = NO2.mean()
    ...
        
        Map.addLayer( meanNO2, band_viz2020, 'S5P NO2 2019');

```
my result:

[![enter image description here][1]][1]

but other organizations without Google Earth Engine, exactly the same date, and their results:

I know this corresponds to L3 and L2 images. Is there a way to solve this problem?
Or how can I connect directly to the sentinel archive in GEE with Python or JavaScript for L2 images?

  [1]: https://i.stack.imgur.com/SPXbg.jpg

![Untitled](https://user-images.githubusercontent.com/31747767/103781221-4c6e5300-504b-11eb-9123-7bb12b73cf97.jpg)

When I change this option {Min. data quality} in EO Browser [https://apps.sentinel-hub.com/eo-browser/](https://apps.sentinel-hub.com/eo-browser/)  ,The gap is reduced

![eo](https://user-images.githubusercontent.com/31747767/103784203-e683ca80-504e-11eb-9570-5aa2a96190a5.jpg)

**Comment by jdbcode** [comment]
S5P L2 data are not available in the Earth Engine Data Catalog. Also, note that the source data is filtered to remove pixels with QA values less than 75% for the `tropospheric_NO2_column_number_density band` of the NO2 products (see [data description](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S5P_OFFL_L3_NO2#description)). 

In the future, please use these links for:

- [Reporting potential data quality issues](https://issuetracker.google.com/issues/new?component=184406&template=1254745)
- [Requesting datasets](https://developers.google.com/earth-engine/help#dataset_requests)
