### ISSUE TITLE
[Consent to Share Developer Resources] geemap, Awesome-GEE

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#315]
@giswqs Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a proposed page under the Community section of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

```
"title": "geemap",
"desc": "A Jupyter-based environment that extends and enhances the Earth Engine Python API using ipyleaflet and ipywidgets. It enables users to analyze and visualize Earth Engine datasets interactively in notebooks.",
"url": "https://geemap.org/",
"contactGitHub": "giswqs"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

To request changes in the future, ping this issue. Thank you for supporting the Earth Engine developer community!

**Comment by giswqs** [comment]
@jdbcode Thanks for the invite! Please see my edits below. The package is still under activate development. New functions are being added weekly. I will continue to develop and maintain the package as long as Earth Engine remains free for research, education, and non-profit use. Thanks. 

```
"title": "geemap",
"desc": "A Jupyter-based environment that extends and enhances the Earth Engine Python API using folium, ipyleaflet, and ipywidgets. It enables users to analyze and visualize Earth Engine datasets interactively in notebooks.",
"url": "https://geemap.org/",
"contactGitHub": "giswqs"
"contactName": "Qiusheng Wu",
"contactConsent": "2021-04-02",
"maintenance": "yes" ,
"development": "yes" ,
```

**Comment by jdbcode** [comment]
Thanks @giswqs! We'd also like to include [Awesome-GEE](https://github.com/giswqs/Awesome-GEE)

Sorry to ask again: is okay that we share the link and description to the resource? If so, can you fill this out (thanks!):

```
"title": "Awesome Earth Engine",
"desc": "A curated list of Google Earth Engine resources.",
"url": "https://github.com/giswqs/Awesome-GEE",
"contactGitHub": "giswqs"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

**Comment by giswqs** [comment]
@jdbcode Yes, please feel free to include it. Many thanks. 

```
"title": "Awesome Earth Engine",
"desc": "A curated list of Google Earth Engine resources.",
"url": "https://github.com/giswqs/Awesome-GEE",
"contactGitHub": "giswqs",
"contactName": "Qiusheng Wu",
"contactConsent": "2021-04-02",
"maintenance": "yes",
"development": "yes",
```

**Comment by jdbcode** [comment]
Thanks! I'll point you to the page when/if it is published. Closing for now, reopen for future changes.

**Comment by jdbcode** [comment]
Thanks for helping support the Earth Engine developer community!

Your resource has been added to the [Developer Resources](https://developers.google.com/earth-engine/tutorials/community/developer-resources) page.

If you'd like to change anything about the title, URL, or description, ping this issue.
