### ISSUE TITLE
[Consent to Share Developer Resources] rgee

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#316]
@csaybar Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a proposed page under the Community section of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

```
"title": "rgee",
"desc": "An R binding package for calling the Earth Engine API from within R. Several functions have been implemented to simplify the connection with the R spatial ecosystem.",
"url": "https://r-spatial.github.io/rgee/"
"contactGitHub": "csaybar"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

To request changes in the future, ping this issue. Thank you for supporting the Earth Engine developer community!

**Comment by csaybar** [comment]
@jdbcode thanks for the consideration of [rgee](https://github.com/r-spatial/rgee) on the developers resources page :). Kindly find attached the information requered.

```
"title": "rgee",
"desc": "An R binding package for calling the Earth Engine API from within R. Several functions have been implemented to simplify the connection with the R spatial ecosystem.",
"url": "https://r-spatial.github.io/rgee/"
"contactGitHub": "csaybar"
"contactName": "Cesar Luis Aybar Camacho",
"contactConsent": "2021-04-02",
"maintenance": "yes",
"development": "yes",
```

Principally this year we will keep focus in provide more documentation ([rgeebook](https://rgeebook.netlify.app/)), solve bugs, and improve the code and unit tests.

**Comment by jdbcode** [comment]
Thanks! I'll point you to the page when/if it is published. Closing for now, reopen for future changes.

rgeebook - it will be great (😍)!

**Comment by jdbcode** [comment]
Thanks for helping support the Earth Engine developer community!

Your resource has been added to the [Developer Resources](https://developers.google.com/earth-engine/tutorials/community/developer-resources) page.

If you'd like to change anything about the title, URL, or description, ping this issue.
