### ISSUE TITLE
[Consent to Share Developer Resources] eemont

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#317]
@davemlz Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a proposed page under the Community section of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

```
"title": "eemont",
"desc": "Convenience helpers for pre-processing and processing Landsat, Sentinel-2, and other popular Earth observation image collections.",
"url": "https://github.com/davemlz/eemont",
"contactGitHub": "davemlz"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

To request changes in the future, ping this issue. Thank you for supporting the Earth Engine developer community!

**Comment by davemlz** [comment]
@jdbcode Thank you very much for the invitation! Here you'll find the requested info. Please note that the package is being constantly updated with new features for the GEE community!

```
"title": "eemont",
"desc": "A Python package that extends the Google Earth Engine Python API with pre-processing and processing tools for the most used satellite platforms by adding new methods for different Earth Engine Objects that are friendly with the Python method chaining.",
"url": "https://github.com/davemlz/eemont",
"contactGitHub": "davemlz"
"contactName": "David Montero Loaiza",
"contactConsent": "2021-04-02",
"maintenance": "yes",
"development": "yes",
```

**Comment by jdbcode** [comment]
Thanks!
Great work on the package!
I'll point you to the page when/if it is published. Closing for now, reopen for future changes.

**Comment by davemlz** [comment]
Thank you, Justin!

**Comment by jdbcode** [comment]
Thanks for helping support the Earth Engine developer community!

Your resource has been added to the [Developer Resources](https://developers.google.com/earth-engine/tutorials/community/developer-resources) page.

If you'd like to change anything about the title, URL, or description, ping this issue.

**Comment by davemlz** [comment]
It looks amazing!

Thank you, Justin!
