### ISSUE TITLE
[Consent to Share Developer Resources] hydra-floods, restee, EarthEngine.jl

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#318]
@KMarkert Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a proposed page under the Community section of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

```
"title": "hydra-floods",
"desc": "An open source Python application for downloading, processing, and delivering surface water maps derived from remote sensing data.",
"url": "https://github.com/Servir-Mekong/hydra-floods",
"contactGitHub": "KMarkert"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

```
"title": "restee",
"desc": "A package that aims to make plugging Earth Engine computations into downstream Python processing easier.",
"url": "https://github.com/KMarkert/restee",
"contactGitHub": "KMarkert"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

To request changes in the future, ping this issue. Thank you for supporting the Earth Engine developer community!

**Comment by KMarkert** [comment]
Thank you for the invitation to have hydrafloods and restee shared on the developers resources page! Please find the requested information below:

```
"title": "hydra-floods",
"desc": "An open source Python application for downloading, processing, and delivering surface water maps derived from remote sensing data.",
"url": "https://github.com/Servir-Mekong/hydra-floods",
"contactGitHub": "KMarkert"
"contactName": "Kel Markert",
"contactConsent": "2021-04-02",
"maintenance": "yes",
"development": "yes"
```
I wanted to note that hydra-floods is a @servir / @servir-mekong package that I lead the development and maintenance on with a lot of help from others. Will there be a way to provide attribution to these organizations and other developers?


```
"title": "restee",
"desc": "A package that aims to make plugging Earth Engine computations into downstream Python processing easier.",
"url": "https://github.com/KMarkert/restee",
"contactGitHub": "KMarkert"
"contactName": "Kel Markert",
"contactConsent": "2021-04-02",
"maintenance": "yes",
"development": "yes"
```

**Comment by jdbcode** [comment]
Thanks, Kel!

Re: hydra-floods attribution - the plan right now is to have a table with the hyperlinked resource name and description, something similar to the following image. The best thing to do is make sure that the provided URL contains attribution, lists orgs and contributors, etc. Sound okay? This GH issue is just to establish consent from a representative contributor/maintainer for sharing and to make sure the resources are described well.

![image](https://user-images.githubusercontent.com/9044197/113431616-df8c0000-9390-11eb-92de-6318abd39528.png)

**Comment by KMarkert** [comment]
Thanks for providing more details. That makes perfect sense and we can make sure all contributors are mentioned in the link. 🙂

**Comment by jdbcode** [comment]
Glad to hear the format is okay!
I'll ping this thread regarding page publication updates. Closing for now, reopen for future changes.

**Comment by jdbcode** [comment]
Thanks for helping support the Earth Engine developer community!

Your resource has been added to the [Developer Resources](https://developers.google.com/earth-engine/tutorials/community/developer-resources) page.

If you'd like to change anything about the title, URL, or description, ping this issue.

**Comment by jdbcode** [comment]
@KMarkert Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a proposed page under the Community section of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

```
"title": "EarthEngine.jl",
"desc": "A Julia programming language interface to Earth Engine",
"url": "https://juliahub.com/docs/EarthEngine",
"contactGitHub": "KMarkert",
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

**Comment by KMarkert** [comment]
Thank you for the invitation to have EarthEngine.jl shared on the developers resources page! Please find the requested information below:

```
"title": "EarthEngine.jl",
"desc": "A Julia programming language interface to Earth Engine",
"url": "https://juliahub.com/docs/EarthEngine",
"contactGitHub": "KMarkert",
"contactName": "Kel Markert",
"contactConsent": "2021-06-03",
"maintenance": "yes" 
"development": "yes"
```

**Comment by jdbcode** [comment]
Thanks! Ping this issue if you want anything changed in the future.
