### ISSUE TITLE
[Consent to Share Developer Resources] QGIS plugin, ee-palettes

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#319]
@gena Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a proposed page under the Community section of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

```
"title": "QGIS Plugin",
"desc": "Integrates Google Earth Engine with QGIS using the Python API.",
"url": "https://github.com/gee-community/qgis-earthengine-plugin",
"contactGitHub": "gena"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

```
"title": "ee-palettes",
"desc": "A module for generating color palettes in Earth Engine to be applied to mapped data.",
"url": "https://github.com/gee-community/ee-palettes",
"contactGitHub": "gena"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

To request changes in the future, ping this issue. Thank you for supporting the Earth Engine developer community!

**Comment by jdbcode** [comment]
@gena sorry to be a pain :) can you post a comment with the following info filled in:

"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",

**Comment by gena** [comment]
```
"title": "ee-palettes",
"desc": "A module for generating color palettes in Earth Engine to be applied to mapped data.",
"url": "https://github.com/gee-community/ee-palettes",
"contactGitHub": "gena"
"contactName": "Gennadii Donchyts",
"contactConsent": "2021-04-02",
"maintenance": "yes",
"development": "yes",
```

```
"title": "QGIS Plugin",
"desc": "Integrates Google Earth Engine with QGIS using the Python API.",
"url": "https://qgis-ee-plugin.appspot.com",
"contactGitHub": "gena"
"contactName": "Gennadii Donchyts",
"contactConsent": "2021-04-02",
"maintenance": "yes",
"development": "yes",
```

**Comment by jdbcode** [comment]
Thanks! :smiley:

**Comment by jdbcode** [comment]
I'll ping this thread regarding page publication updates. Closing for now, reopen for future changes.

**Comment by jdbcode** [comment]
Thanks for helping support the Earth Engine developer community!

Your resource has been added to the [Developer Resources](https://developers.google.com/earth-engine/tutorials/community/developer-resources) page.

If you'd like to change anything about the title, URL, or description, ping this issue.
