### ISSUE TITLE
[Consent to Share Developer Resources] gee-ccdc-tools

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#320]
@parevalo Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a proposed page under the Community section of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

```
"title": "gee-ccdc-tools",
"desc": "A suite of tools designed for continuous land change monitoring in Google Earth Engine.",
"url": "https://gee-ccdc-tools.readthedocs.io/en/latest",
"contactGitHub": "parevalo"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

To request changes in the future, ping this issue. Thank you for supporting the Earth Engine developer community!

**Comment by parevalo** [comment]
Here's the requested info:

```"title": "gee-ccdc-tools",
"desc": "A suite of tools designed for continuous land change monitoring in Google Earth Engine.",
"url": "https://gee-ccdc-tools.readthedocs.io/en/latest",
"contactGitHub": "parevalo"
"contactName": "Paulo Arévalo",
"contactConsent": "2021-04-03",
"maintenance": "maybe",
"development": "maybe"```

**Comment by jdbcode** [comment]
Thanks for the info!
I'll ping this thread regarding page publication updates. Closing for now, reopen for future changes.

**Comment by jdbcode** [comment]
Thanks for helping support the Earth Engine developer community!

Your resource has been added to the [Developer Resources](https://developers.google.com/earth-engine/tutorials/community/developer-resources) page.

If you'd like to change anything about the title, URL, or description, ping this issue.
