### ISSUE TITLE
[Consent to Share Developer Resources] awesome-gee-community-datasets

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#322]
@samapriya Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a proposed page under the Community section of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

```
"title": "Awesome GEE Community Datasets",
"desc": "A curated list of community-hosted datasets.",
"url": "https://github.com/samapriya/awesome-gee-community-datasets",
"contactGitHub": "samapriya",
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

To request changes in the future (including suggestions for additional resources), ping this issue. Thank you for supporting the Earth Engine developer community!

A preview of what the section will likely look like:
![image](https://user-images.githubusercontent.com/9044197/113447196-3ce27a00-93ae-11eb-9786-804bf13eff44.png)

**Comment by samapriya** [comment]
Hope this is what you need 

```
"title": "Awesome GEE Community Datasets",
"desc": "A curated list of community-hosted datasets in Google Earth Engine",
"url": "https://github.com/samapriya/awesome-gee-community-datasets",
"contactGitHub": "samapriya",
"contactName": "Samapriya Roy",
"contactConsent": "2021-04-02",
"maintenance": "yes",
"development": "yes",
```

**Comment by jdbcode** [comment]
Looks great - thank you!

**Comment by jdbcode** [comment]
I'll ping this thread regarding page publication updates. Closing for now, reopen for future changes.

**Comment by jdbcode** [comment]
Thanks for helping support the Earth Engine developer community!

Your resource has been added to the [Developer Resources](https://developers.google.com/earth-engine/tutorials/community/developer-resources) page.

If you'd like to change anything about the title, URL, or description, ping this issue.
