### ISSUE TITLE
[Consent to Share Developer Resources] End-to-End Google Earth Engine

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#335]
@spatialthoughts Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a page under the [Community section](https://developers.google.com/earth-engine/tutorials) of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource (if applicable)
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

---

### Spatial Thoughts

**End-to-End Google Earth Engine**

[This course](https://spatialthoughts.com/courses/google-earth-engine/) by [Ujaval Gandhi](https://spatialthoughts.com/about/), founder of [Spatial Thoughts](https://spatialthoughts.com/), covers the full range of topics in Earth Engine to give participants practical skills to master the platform and implement their remote sensing projects.

It includes 16 hours of live instruction (typically 4 sessions of 4 hours each) with 8 hours of self-study materials (videos and guided projects).

```
"contactGitHub": "spatialthoughts",
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

**Comment by spatialthoughts** [comment]
The suggested snippet looks good. I do plan to maintain and update the resource on an ongoing basis. Please find the other data below.

```
"contactGitHub": "spatialthoughts",
"contactName": "Ujaval Gandhi",
"contactConsent": "2021-05-08",
"maintenance": "yes",
"development": "yes"
```

**Comment by spatialthoughts** [comment]
Hi Justin - There has been some updates to this course and  would like to update the text as follows

It includes 24 hours of live instruction (typically 6 sessions of 4 hours each) and includes a wide range of hands-on exercises.

**Comment by jdbcode** [comment]
Hi Ujaval! Just wanting to confirm, is this the change to make?

From:
> It includes 16 hours of live instruction (typically 4 sessions of 4 hours each) with 8 hours of self-study materials (videos and guided projects).

To:
> It includes 24 hours of live instruction (typically 6 sessions of 4 hours each) and includes a wide range of hands-on exercises.

**Comment by spatialthoughts** [comment]
Yes. That looks good.

**Comment by jdbcode** [comment]
Great, the edit has been made. The change should be live in the next couple of days.

**Comment by jdbcode** [comment]
The changes are live: https://developers.google.com/earth-engine/tutorials/ttt#end-to-end-google-earth-engine
Closing for now, reopen for further edits.
