### ISSUE TITLE
Issue with tutorials/nonparametric-trends/index.md

### ISSUE THREAD

**Issue by lfper** [google/earthengine-community#346]
Hello everyone! I have used a identical copy of the code available on this tutorial (https://developers.google.com/earth-engine/tutorials/community/nonparametric-trends) to perform a mann-kendall test and compute p-values. 

Today i have noticed a bug which is making my p-values negative. I have made no changes since the last time i used this code, and i could not find any prolem in my script. 

I would really appreciate some help! 

Best regards, 

Luís Pereira

**Comment by jdbcode** [comment]
Hi @lfper!
I see you closed the issue without comment. Does this mean that there is no problem?

**Comment by lfper** [comment]
Hi mister Braaten! Yes, a collaborator found a problem with my code, which
was edited without my knowledge. I'm sorry for that! The original code is
working.

Thanks for asking!

Luís

Em qua, 2 de jun de 2021 14:17, Justin Braaten ***@***.***>
escreveu:

**Comment by jdbcode** [comment]
Thanks for confirming :)
