### ISSUE TITLE
Issue with tutorials/extract-raster-values-for-points/index.md

### ISSUE THREAD

**Issue by ntmt2903** [google/earthengine-community#355]
zonalStats function throws an "fc.filterBounds is not a function" error when I tried it 😞
![_GEE_feedback](https://user-images.githubusercontent.com/54069026/121342484-dd738e00-c94b-11eb-8ac0-6c79317e9f6e.jpg)

**Comment by jdbcode** [comment]
Hello @ntmt2903 - thanks for getting in touch!

I can't reproduce the error using the feature collection provided in the tutorial ([script](https://code.earthengine.google.com/f7468ca8a82a129b78a0ffbad1023568)). Are you using a different feature collection for defining zones? Can you please share the script, if possible, so I can try to reproduce and debug (please ensure any imported assets are shared publicly, at least temporarily).

**Comment by ntmt2903** [comment]
Yes, I'm using a different feature collection, but forgot to define it as a FeatureCollection -.- [my script](https://code.earthengine.google.com/c97e67cf9fb74a9df0ac37a6580f4246). I got the result now. Thank you for the tutorial, it really helps!

**Comment by jdbcode** [comment]
Happy to hear you got it working!
