### ISSUE TITLE
Issue with tutorials/extract-raster-values-for-points/index.md

### ISSUE THREAD

**Issue by NeverDelay001** [google/earthengine-community#372]
Issue Description
In the process of extracting the value of the landsat image using my own vector points, the value of 3000 vector points is always only 1000 points is mentioned in the csv file, how can I set it not to filter out the remaining 2000 points, but to all The buffer values of the points are brought up.

**Comment by gino-m** [comment]
HI @gifford27, sorry for the extremely delayed response, we haven't been regularly monitoring this channel. Can you please post your question to one of our supported channels, providing a link to the modified notebook. You can find out more here:
https://developers.google.com/earth-engine/help
