### ISSUE TITLE
Please someone can help me to extract a value of forest loss?

### ISSUE THREAD

**Issue by donaldfossi** [google/earthengine-community#385]
**What is the objective of the proposed tutorial?**
A clear and concise description of what users can expect to learn from your
tutorial.

**What is the scope of the proposed tutorial?**
The thematic (forestry, water resources, land cover classification, Earth Engine
core libraries, etc) and specific geographic area, if relevant.

**Please provide an outline of the structure of the proposed tutorial?**
1. Section 1
  a. Subsection 1a
  b. Subsection 1b
2. Section 2
  .. et cetera. ..

**In what format will you be submitting the tutorial?**
Select one: [Markdown](https://guides.github.com/features/mastering-markdown/)
or [Colab](https://research.google.com/colaboratory/faq.html)

This request will be reviewed by the Earth Engine community maintainers, who
will reply on this issue tracker with any questions or suggestions. Once
approved, this issue will be assigned to you and you can begin work on the
tutorial following instructions in
[Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write).
When creating your Pull Request, enter "Closes #issueno" in the description of
your Pull Request to link the tutorial to this issue.

**Comment by tylere** [comment]
Closing, since this doesn't appear to be a tutorial proposal.

For general Earth Engine support, please follow the instructions at: https://developers.google.com/earth-engine/help
