### ISSUE TITLE
[Consent to Share Developer Resources] wxee, sankee, snazzy

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#395]
@aazuspan Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a proposed page under the Community section of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

```
"title": "wxee",
"desc": "A Python interface between Earth Engine and xarray for processing weather and climate data.",
"url": "https://github.com/aazuspan/wxee",
"contactGitHub": "aazuspan"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

```
"title": "sankee",
"desc": "Visualize classified time series data with interactive Sankey plots in Google Earth Engine.",
"url": "https://github.com/aazuspan/sankee",
"contactGitHub": "aazuspan"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

To request changes in the future, ping this issue. Thank you for supporting the Earth Engine developer community!

**Comment by aazuspan** [comment]
Thanks @jdbcode!

```
"title": "wxee",
"desc": "A Python interface between Earth Engine and xarray for processing weather and climate data.",
"url": "https://github.com/aazuspan/wxee",
"contactGitHub": "aazuspan"
"contactName": "Aaron Zuspan",
"contactConsent": "2021-09-08",
"maintenance": "yes",
"development": "yes",
```
```
"title": "sankee",
"desc": "Visualize classified time series data with interactive Sankey plots in Google Earth Engine.",
"url": "https://github.com/aazuspan/sankee",
"contactGitHub": "aazuspan"
"contactName": "Aaron Zuspan",
"contactConsent": "2021-09-08",
"maintenance": "yes",
"development": "yes",
```

**Comment by jdbcode** [comment]
Thank you @aazuspan!
The entries will be published to https://developers.google.com/earth-engine/tutorials/community/developer-resources soon. I'll ping this thread when the changes are live.

**Comment by jdbcode** [comment]
@aazuspan your packages are now included in the Developer Resources page
https://developers.google.com/earth-engine/tutorials/community/developer-resources#python

If you want to make changes to the entries in the future, ping this thread.

Thanks for supporting the Earth Engine developer community!

**Comment by aazuspan** [comment]
Thanks Justin!

**Comment by jdbcode** [comment]
@aazuspan Thanks for accepting Earth Engine RevRel’s request to share your developer resource(s) in a proposed page under the Community section of the Developer's Guide.

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent
3. let us know your plans for maintenance and development of your resource

```
"title": "snazzy",
"desc": "Snazzy basemaps in the Earth Engine Code Editor.",
"url": "https://github.com/aazuspan/snazzy",
"contactGitHub": "aazuspan",
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

To request changes in the future, ping this issue. Thank you for supporting the Earth Engine developer community!

**Comment by aazuspan** [comment]
Here you go @jdbcode. Thanks!

```
"title": "snazzy",
"desc": "Snazzy basemaps in the Earth Engine Code Editor.",
"url": "https://github.com/aazuspan/snazzy",
"contactGitHub": "aazuspan",
"contactName": "Aaron Zuspan",
"contactConsent": "2022-03-22",
"maintenance": "yes",
"development": "yes",
```

**Comment by jdbcode** [comment]
Aaron, snazzy has been added to the list of developer resources: https://developers.google.com/earth-engine/tutorials/community/developer-resources#modules

Comment on this issue if you'd like anything about your resource entries changed in the future.

Thanks for supporting the EE Developer community!

**Comment by aazuspan** [comment]
Awesome, thanks Justin!
