### ISSUE TITLE
[Tutorial proposal] Exploring S1 archive in Colab

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#408]
(Capturing an email thread for a potential tutorial from @mortcanty)
The idea is to use the new widgets capabilities in Colab for exploring the S1 archive.

There are limitations on what types of outputs can be displayed in the Community Tutorials pages, e.g. widgets. @gino-m has worked out a solution to deal with this: allow a screenshot to be displayed in cases where live outputs fail, but the screenshot is not displayed in the Colab notebook, so that readers can view the output natively (without the odd duplication of a static screenshot).

@mortcanty is okay with this solution.

Next step is for @mortcanty to provide a Colab notebook that has example widgets for us to test (possibly not a complete draft, in case other challenges arise, maybe better to make incremental progress to a complete initial draft).

**Comment by mortcanty** [comment]
Hi Justin and Gino,
I Just copied to you the link to the (more or less) final version of the tutorial. I can go through the fork/clone/pull request stuff whenever you think it's ready. 

Best
Mort

**Comment by jdbcode** [comment]
Hi Mort, checking in again. Gino has been able to generate the DevSite outputs from the notebook with the new implementation that substitutes static images when live outputs cannot be rendered. However, the "output" for the widget with the selectors is not working as intended. Gino is investigating, but having to balance with other work. We'll keep you updated as we know more.

**Comment by mortcanty** [comment]
Thanks for the update Justin. Not sure I understand the intention. Will the DevSite version offer some kind of interactive functionality? Otherwise why not just show a screenshot with a "Requires Colab" label? Anyway, sorry it's causing you guys so much work. Best, Mort

**Comment by jdbcode** [comment]
Hi Mort, unfortunately there has been no progress. We're just coming off preparing for and hosting our annual Geo for Good summit.

The issue we're hung up on is a relatively minor one: we can't render the S1 explorer widget in our DevSite pages, so we have a fallback option to display a screenshot when an output cannot be rendered, but in the case of your tutorial, two non-widget outputs from the... 

```
# Run the interface
from eesar.application import run
run()
```

...cell _are_ being rendered, so therefor the fallback screenshot output of the cell (the explorer widget) is not appearing. The concern is that the outputs that are being rendered might be confusing to readers of the tutorial when viewing the DevSite version.

![image](https://user-images.githubusercontent.com/9044197/144322376-931a4939-b151-4c56-ab49-1e6267e84820.png)

I feel like we've stalled out on this and should publish the tutorial despite this behavior and work to resolve it sometime in the future. I assume that most people will be viewing the Colab version anyway so that they can run the cells themselves and interact with the S1 explorer.

Will you please submit a pull request that includes the most recent version of the .ipynb file (the last one we saw was: https://colab.sandbox.google.com/drive/1bcuhdYU3d6CTLuwa_1hYiJtbElNcw3mF). I'm happy to help walk you through the pull request process if you need any assistance--just let me know.

**Comment by mortcanty** [comment]
Will do. And again, sorry for the trouble.

**Comment by jdbcode** [comment]
Thanks, Mort! I just quickly looked at the PR, everything looks in order for me to do the review. My goal is to provide initial comments by end-of-day tomorrow.
