### ISSUE TITLE
[Tutorial proposal] Estimating Groundwater Recharge Using Earth Engine Datasets

### ISSUE THREAD

**Issue by guiattard** [google/earthengine-community#414]
Hello everyone, 

I would like to submit you the idea of a new tutorial that could fit into the pyhton section of the earth egine community tutorials.

**What is the objective of the proposed tutorial?**
The objective of the tutorial is to calculate groundwater recharge rate at a given location using (1) meteorological datasets and (2) soil profile datasets.

In this tutorial, users will learn how to access (1) physical properties of soil around a place and (2) meteorological records to feed an iterative procedure implemented outside of the eath engine environment.

**What is the scope of the proposed tutorial?**
This tutorial focus on water resources management.

**Please provide an outline of the structure of the proposed tutorial?**
*1. Introduction*
- why calculating groundwater recharge
- aim and structure of the tutorial

*2. Run me first*
- initialization of theearth engine API, 
- import of librairies
- definition of the location and period of interest and visualization with folium

*3. Getting soil properties*
- introduction to Saxton & Rawls (2006) equations to link hydraulic properties of soil to texture properties,
- exploration of soil texture datasets (OpenLandMap)
- definition of a function to get the soil texture and content for a given location,
- definition of a function to calculate the wilting and field capacity of soil,

*4. Getting meteorological records*
- definition of a function to get precipitation and potential evapotranspiration records for a given location
- transformation into a dataframe

*5. Implementation of the Thornwaite-Mather (TM) procedure*
- description of the TM procedure to calculate groundwater recharge
- definition of a function to run the TM procedure. 
- calculation of the recharge at our location of interest

*6. Compilation and comparison between multiple places*
- definition of un function combining all steps and function previously defined,
- calculation and comparison of groundwater recharge fluctuations between two places.

*7. Bibliography*
- list of references used in the tutorial

**In what format will you be submitting the tutorial?**
[Colab]

Best regards,

This request will be reviewed by the Earth Engine community maintainers, who
will reply on this issue tracker with any questions or suggestions. Once
approved, this issue will be assigned to you and you can begin work on the
tutorial following instructions in
[Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write).
When creating your Pull Request, enter "Closes #issueno" in the description of
your Pull Request to link the tutorial to this issue.

**Comment by jdbcode** [comment]
Hi @guiattard great to hear from you again!
Just a short message to let you know that we got your proposal.
We'll be looking at it in the next few days.
Thanks for your patience :)

**Comment by jdbcode** [comment]
Thanks for the well-planned proposal! We think it would be a valuable, applied tutorial and would like to work with you to get it published.

Could you clarify two things:

1. what packages will you be importing?
2. you state "meteorological records to feed an iterative procedure implemented outside of the earth engine environment", can you describe this more, it would be nice if everything was runnable from within a Colab notebook (will it be?).

**Comment by guiattard** [comment]
Hi,

1. He are the following packages that will be imported: pandas, numpy, matplotlib, folium and datetime
2. Everything will be runnable from within a Colab notebook. Let me be more specific about what users could learn from this tutorial:
- in section 3, users will manipulate openLandMap datasets describing soil properties (e.g. sand and clay content) and will use .expression() to get a global image describing wilting point and field capacity of soils  (the hydraulic properties of soil we are interested in).
- in section 4, users will have to resample a daily precipitation dataset to a 8-days basis one to fit an evapotranspiration dataset. We adress that applying a .map() method over the precipitation ImageCollection.
- Once we have a global image of hydrauic properties of soil, and the synchronous precipitation/evapotranspiration ImageCollection, an iterative process will be implemented in section 5. The idea is to make a water buget based on the Thornthwaite-Matter procedure to calculate groundwater recharge. Currently, I've made the script for one point. It is working well but I am working on a way to implement the iterative process using the .iterate() method over precipitation/evapotranspiration ImageCollection to make the calculation global (and not only local).

I hope it is almost clear now ;-)

Regards,

**Comment by jdbcode** [comment]
Thanks for the clarification. This is all fine, please proceed with completing the tutorial following [these instructions](https://developers.google.com/earth-engine/tutorials/community/write#colab-notebook) (same as last time). Let us know if you need anything from us. We'll look forward to your pull request!

**Comment by guiattard** [comment]
Good! I have few things to add and organise. I'll probably be ready for submission within the next two/three weeks.

Regards

**Comment by guiattard** [comment]
Hi @jdbcode,

Just a quick reminder. Is everything fine with my PR #418 ?

Regards,

**Comment by jdbcode** [comment]
Hi @guiattard, sorry for the delay, I was offline last week. I'll be doing an initial review of the tutorial in the next few days.
