### ISSUE TITLE
Issue with tutorials/detecting-changes-in-sentinel-1-imagery-pt-2/index.ipynb

### ISSUE THREAD

**Issue by guiattard** [google/earthengine-community#444]
Hello everyone, 

I've been through the the python tutorial series focusing on sentinel-1. Thanks to the contributors and @mortcanty for this detailed and very interesting work. I would only have one recommandation to make easier the adaptation of the tutorial (part 2) to a user-specific area of interest (and different from the site proposed in the tutorial).

At the beginnig of the tutorial, the area of interest is defined as a polygon and just after that, the S1 image collection is filtered accordingly. In this procedure, the relative orbit number of interest (equal to `15`) is specified but seems to come out of nowhere (see below).

```
im_coll = (ee.ImageCollection('COPERNICUS/S1_GRD_FLOAT')
                .filterBounds(aoi)
                .filterDate(ee.Date('2020-08-01'),ee.Date('2020-08-31'))
                .filter(ee.Filter.eq('orbitProperties_pass', 'ASCENDING'))
                .filter(ee.Filter.eq('relativeOrbitNumber_start', 15))
                .sort('system:time_start'))
```
To people not very familiar with the S1 product, it might be confusing and hard to understand how to adapt the number to the actual area of interest. Hence, I would recommand to add a line or a link to give an indication in that sence.

For example, I think that a reference to the [Acquisition Plan Viewer](https://app.spectator.earth/acquisition-plan?@49.36806633482156,3.4277343750000004,5z) might be helpfull to find relative orbit number associated to satellites, period and locations of interest.

Otherwise, the S1 series is great =)

Best regards,

**Comment by jdbcode** [comment]
Good suggestion. I wonder if it is necessary? It seems not. There is a date and aoi filter, which seems sufficient. I'll try without the `relativeOrbitNumber_start` and see if a different set of images are provided. In any case, it seems unnecessary for the purpose of the tutorial.

**Comment by jdbcode** [comment]
Best to keep the filter for relative orbit. I added a note where they can find relative orbit, see #768 (thanks for the suggestion about Acquisition Plan Viewer!)
