### ISSUE TITLE
Issue with tutorials/forest-cover-loss-estimation/index.md

### ISSUE THREAD

**Issue by ulfboge** [google/earthengine-community#490]
Dear GEE-community,

In the GEE Community tutorial "[Forest Cover and Loss Estimation](https://developers.google.com/earth-engine/tutorials/community/forest-cover-loss-estimation)" -> "Subsequent tree cover", it says:

"You can estimate the tree cover after the loss by subtracting the loss from the previous tree cover."

When I look at [globalforestwatch.org/map](https://www.globalforestwatch.org/map/), under the "Caution" section on the "Tree cover loss 2001-2020" information tab, it says:

"Due to variation in research methodology and date of content, tree cover, loss, and gain data sets cannot be compared accurately against each other. Accordingly, "net" loss cannot be calculated by subtracting figures for tree cover gain from tree cover loss, and **current (post-2000) tree cover cannot be determined by subtracting figures for annual tree cover loss from year 2000 tree cover**."

To me, these are two contradictory statements on one type of analysis. Or am I missing something here? Is it "estimate" and " be determined" that separates the two statements?

Kind regards,
Johan

**Comment by jdbcode** [comment]
Johan, thanks for flagging the issue (and moving the info here 😃) . I'll look more closely and propose some ways to resolve it by the end of the week.

**Comment by ulfboge** [comment]
Dear Justin,
Just wanted to check-in on the progress of this issue? :)
Thanks,
Johan

**Comment by nkeikon** [comment]
@jdbcode, thanks for tagging and suggesting good options!

As you said, this tutorial is meant to provide tools to conduct the analysis and the datasets should be any that's most suited. In reality, when the government conducts this type of analyses, they typically have a wall-to-wall national tree cover map (For more information and examples, please see [FREL submissions by countries](https://redd.unfccc.int/submissions.html?topic=6)). Many of them still use the Hansen datasets to varying degree, but when they do, they correct bias with statistical sampling. What I mean by saying all this is that the proper analyses for the subject matter takes a lot more than what the tutorial provides, which is to show how to incorporate the tree loss in estimating the administratively defined 'forest' cover by coding. 

I think that it's a good idea to add the acknowledgement (option 3). I'd also add a few sentences when we are introducing the datasets.

In the subsection starting with 'Tree cover', it says:

> Currently, Google Earth Engine has several tree cover datasets in the catalogue, including the Global Forest Change (GFC) (year 2000) and GLCF: Landsat Tree Cover Continuous Fields (2000, 2005, and 2010). Here, we use the Global Forest Change dataset.

Instead the above, what do you think about saying something like:

> We need a tree cover map to start this analysis. It is important to select a tree cover map that is appropriate for the purpose and scope of your research. In this tutorial, we select one from the Google Earth Engine catalogue, which currently has several tree cover datasets in the catalogue, including the Global Forest Change (GFC) (year 2000) and GLCF: Landsat Tree Cover Continuous Fields (2000, 2005, and 2010). Here, we use the Global Forest Change dataset*. 
*"We acknowledge that <https://github.com/google/earthengine-community/issues/490#issue-1177277759>; the dataset is used to demonstrate analyses and introduce Earth Engine concepts"

Thanks so much for your help!

**Comment by jdbcode** [comment]
This all sounds great, Keiko, thanks!
I'm just about to be off on vacation for a week, so will need to make the change after I return.
I'll run the pull request by you.

**Comment by jdbcode** [comment]
@gino-m please review #765
