### ISSUE TITLE
Tutorial Request: LULC classification and Accuracy assessment 

### ISSUE THREAD

**Issue by varsh786** [google/earthengine-community#496]
Hello,
I am a graduate level student and working on gee for a project. I am not getting the expected results in my LULC classification. Please do share a video tutorial on how it is done.
Thank you.

**Comment by jdbcode** [comment]
Hi @varsh786, please register your questions with either the Earth Engine Developer's Forum or the Earth Engine component of GIS Stack Exchange. You can find links to these resources and learn more about how to route your questions on our [Help](https://developers.google.com/earth-engine/help#ask_a_question) page.

Best,
Justin
