### ISSUE TITLE
Issue with tutorials/groundwater-recharge-estimation/index.ipynb

### ISSUE THREAD

**Issue by guiattard** [google/earthengine-community#510]
Hello everyone,

Since few days, I noticed some graphical issues with the above mention tutorial [here](https://developers.google.com/earth-engine/tutorials/community/groundwater-recharge-estimation)

**First issue:**
At the begining, everything looks good, especially formulas. But after some point, i can see a '{% endframebox %}' and all formulas after become unreadable (see the screenshot below):

![image](https://user-images.githubusercontent.com/49778819/166231519-6df66f64-913b-48af-881a-3661fccf6cb0.png)

**Second issue:**
The interactive folium outputs look to be down.

Regards

**Comment by gino-m** [comment]
Looking into this now. Thanks for reporting!

**Comment by guiattard** [comment]
It looks perfect!

Thanks!

**Comment by gino-m** [comment]
Great, thanks for taking a look. Marked closed!
