### ISSUE TITLE
Tutorial Request: <Landsat 5 free cloud composite in tropical island area (borneo island)>

### ISSUE THREAD

**Issue by Ramdhani26** [google/earthengine-community#532]
I'm having trouble getting a cloud-free image of Landsat 5 for the tropical area (borneo Island), I tried using a script from GEE but the results are still not satisfactory. any other suggestions or scripts? here attached script I used: https://code.earthengine.google.com/e13d65a013420a20c23993236946bf24

any suggestion?

**Comment by gino-m** [comment]
Hi @Ramdhani26! I believe you meant to ask for support. Please check out this page for several ways to get help with using Earth Engine:
https://developers.google.com/earth-engine/help
