### ISSUE TITLE
Expected an assignment or function call and instead saw an expression.

### ISSUE THREAD

**Issue by imhunterand** [google/earthengine-community#547]
Any statement (other than a null statement, which means a statement containing only a semicolon ;) which has no side effect and does not result in a change of control flow will normally indicate a programming error, and therefore should be refactored.

```javascript
// [START earthengine__tutorial_0__function]
var myFunction = function(parameter1, parameter2, parameter3) {
statement;
```

[MITRE, CWE-482](https://cwe.mitre.org/data/definitions/482) - Comparing instead of Assigning

**Comment by jdbcode** [comment]
This is just a foo example for how to define a function. You can see the code block in context in the [Introduction to JavaScript for Earth Engine](https://developers.google.com/earth-engine/tutorials/tutorial_js_01). The code block following this instructional function definition is a working example so developers can see how a function works in practice. If you have further ideas for documentation improvements please leave feedback on the relevant page.
![image](https://user-images.githubusercontent.com/9044197/180652447-1f5add65-c59e-40b6-9cbe-1bf63dd1cc92.png)
