### ISSUE TITLE
[Consent to Share Developer Resources] spectral

### ISSUE THREAD

**Issue by jdbcode** [google/earthengine-community#565]
@davemlz Thanks for suggesting Awesome Spectral Indices be included in Earth Engine's [Developer Resources page](https://developers.google.com/earth-engine/tutorials/community/developer-resources).

Please:

1. edit the provided suggestions for how to present your resource
2. add your name and date to confirm your consent to display your resource
3. let us know your plans for maintenance and development of your resource

```
"title": "Awesome Spectral Indices",
"desc": "A standardized ready-to-use curated list of spectral indices that can be used as expressions for computing spectral indices in GEE.",
"url": "https://github.com/awesome-spectral-indices/spectral",
"contactGitHub": "davemlz"
"contactName": "YOUR NAME",
"contactConsent": "YYYY-MM-DD",
"maintenance": "yes" OR "no" OR "maybe",
"development": "yes" OR "no" OR "maybe",
```

To request changes in the future, ping this issue. Thank you for supporting the Earth Engine developer community!

**Comment by davemlz** [comment]
Thanks a lot, Justin! Here is the requested info. The module is fully operational, maintained, and I will keep adding features in the future! :)

```
"title": "spectral",
"desc": "A module for accessing and computing spectral indices from Awesome Spectral Indices inside the Code Editor",
"url": "https://github.com/awesome-spectral-indices/spectral",
"contactGitHub": "davemlz",
"contactName": "David Montero Loaiza",
"contactConsent": "2022-09-16",
"maintenance": "yes",
"development": "yes",
```

**Comment by davemlz** [comment]
Thank you very much, Justin!

**Comment by jdbcode** [comment]
It's live! 🚀 
https://developers.google.com/earth-engine/tutorials/community/developer-resources

Ping this thread if you want to make changes to the entry in the future.

**Comment by davemlz** [comment]
That was super fast!

Thank you, Justin! :rocket:
