### ISSUE TITLE
Bitemporal Change Detection on GEE with the iMAD Algorithm

### ISSUE THREAD

**Issue by mortcanty** [google/earthengine-community#571]
**What is the objective of the proposed tutorial?**
The Multivariate Alteration Detection (MAD) algorithm was proposed and developed some time ago by Allan Nielsen and his coworkers at the Technical University of Denmark and later extended to an iterative version (iMAD). It has since found widespread application for the generation of change information as well as for performing relative radiometric normalization of optical/infrared imagery. Particularly with the development of the fantastic tools available in Google Earth Engine (GEE) it is easy to generate reflectance time series animations from satellite imagery which show changes quite dramatically. Such visualizations are very good as eye-openers to give a conceptual, qualitative impression of change. This may, however, be perceived differently from person to person. With rigorous statistical methods on the other hand one can derive formal, quantitative and reproducible change information on both pixel and patch/field levels. The iMAD algorithm is one such method.

**What is the scope of the proposed tutorial?**
I propose to structure the tutorial similarly to my previous SAR tutorials. It is based on the description of iMAD given in Chapter 9 of my textbook Image Anaylsis, Classification and Change Detection in Remote Sensing. In preparing it I intend to take as much advantage as possible of the GEE platform to illustrate and demonstrate the theory interactively . 

**Please provide an outline of the structure of the proposed tutorial?**
The tutorial will be an elaboration of one written in April,2021 and advertised on Twitter, see the Gist
https://gist.github.com/mortcanty/1f5b1924dd655944c9866ec74c657820
Part 1. Bitemporal change detection and radiometric normalization, the iMAD algorithm
Part 2. Unsupervised classification of change images
Part 3. Applications, including  a Jupyter widget interface for exploration of the GEE archive: Sentinel, Landsat.
 

**In what format will you be submitting the tutorial?**
[Colab](https://research.google.com/colaboratory/faq.html)

This request will be reviewed by the Earth Engine community maintainers, who
will reply on this issue tracker with any questions or suggestions. Once
approved, this issue will be assigned to you and you can begin work on the
tutorial following instructions in
[Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write).
When creating your Pull Request, enter "Closes #issueno" in the description of
your Pull Request to link the tutorial to this issue.

**Comment by mortcanty** [comment]
Any remarks, or does this stuff just have low priority at present? Thanks, Mort

**Comment by jdbcode** [comment]
Hi again, Mort! It was great to hear that you were working with David on SAR change detection. I hope that all went okay.
Sorry for the slow reply, I think we were doing our annual Geo for Good user summit the week to posted this and now finally getting through the backlog.

This looks great! Please proceed to preparing the notebook and submitting a PR. It looks like you have a lot of the work done already (based on the gist you shared). I see that you are using folium for the map, which is great; however, wanting to let you know that @tylere is developing a library of helpers for displaying and inspecting maps in Jupyter env that provides some shortcuts - you might try using it (certainly not necessary though). Here is a Colab notebook showing some of its basic usage - see sections on map vis and inspecting: https://colab.research.google.com/drive/14h1C_chywvYr1_LFltx7d7YHOMSDAKHV?usp=sharing

**Comment by mortcanty** [comment]
Thanks for the go-ahead, Justin.

I had intended to use ipyleaflet rather than folium anyway, and Tyler's library looks really good. In the tutorial I want to elaborate and extend the stuff in the gist and especially look in more detail at clustering and interpretation of the MAD change images.

The 4 months with David and Trent were certainly fun for me. I hope Google got its money's worth :-)

Mort

**Comment by jdbcode** [comment]
We've been publishing these, closing.
