### ISSUE TITLE
Issue with tutorials/landsat-etm-to-oli-harmonization/index.md

### ISSUE THREAD

**Issue by fengfalai** [google/earthengine-community#591]
Hello, landsat has stopped updating Collection 1 products and started producing Collection 2 products. Can all new products migrate this harmonization method? if not, how should Collection 2 implement Collection 2? thank you for what you have done and look forward to your reply.

**Comment by jdbcode** [comment]
Harmonization coefficients like those described in the tutorial have not been published for Collection 2 and it is not clear that they are needed ([see this note](https://developers.google.com/earth-engine/faq#is_cross-sensor_landsat_surface_reflectance_harmonization_needed)). The tutorial is hidden from the table of contents and considered deprecated and won't be updated ([see note at top of tutorial](https://developers.google.com/earth-engine/tutorials/community/landsat-etm-to-oli-harmonization)).
