### ISSUE TITLE
[Tutorial proposal] Pseudo-invariant feature matching in Earth Engine

### ISSUE THREAD

**Issue by aazuspan** [google/earthengine-community#611]
**What is the objective of the proposed tutorial?**
Apply relative radiometric normalization using [pseudo-invariant feature matching](https://www.sciencedirect.com/science/article/abs/pii/0034425788901162).

**What is the scope of the proposed tutorial?**
A pair of public SkySat images acquired before and after forest conversion in Peru. JS API.

**Please provide an outline of the structure of the proposed tutorial?**
1. Intro
    1. Change detection and radiometric normalization
        1. Explanation and applications
        2. PIF compared to  [histogram matching](https://developers.google.com/earth-engine/tutorials/community/histogram-matching)  
    2. Loading data
        1. Before and after images from SkySat
3. Detecting Pseudo-Invariant Features
    1. Calculating spectral distance
    2. Identifying stable pixels
        1. Percentile reducer
4. Applying Normalization
    1. Band-wise linear fitting
        1. Mapping over bands and combining into an image 
6. Results

**In what format will you be submitting the tutorial?**
Markdown

Here's a draft of the [JS script](https://code.earthengine.google.com/b002f7ceec1c474682ee86811bd3800c) that I would be going over.

**Comment by aazuspan** [comment]
Hey Justin, I'm still happy to write this up. I'll make a PR when it's ready.

**Comment by jdbcode** [comment]
That sounds great! Wanting to respect your time, no need to go into too much detail on the text, sometimes less is more. Always opportunities to expand on detail in future edits.
