### ISSUE TITLE
Tutorial Request: <FwDET 2.1 Flood Water Depth Estimations Tool>

### ISSUE THREAD

**Issue by zeenatyasmeen** [google/earthengine-community#634]
Desscussion

Technical Level
beginner | intermediate | advanced

Length
short (< 250 words) | medium (250-500 words) | long (1000 words )

**Comment by gino-m** [comment]
Hi @zeenatyasmeen, this form is intended for expressing your interest in_writing a new tutorial. For general questions or requests, please consider posting to https://stackoverflow.com/questions/tagged/google-earth-engine or https://groups.google.com/g/google-earth-engine-developers. Thanks!
