### ISSUE TITLE
Tutorial Request: <FwDET2.0>

### ISSUE THREAD

**Issue by zeenatyasmeen** [google/earthengine-community#647]
Dear Community Fellows,
Iam a hydro meteorologist, currently working on the Flood water depth estimation of Pakistan 2022 flood due to Summer monsoon.
If any one have a material and tutorial regarding this may kindly share on zeenatpmd09@gmail.com 

Technical Level
beginner | intermediate | advanced

Length
short (< 250 words) | medium (250-500 words) | long (1000 words )

**Comment by gino-m** [comment]
Hi @zeenatyasmeen, this form is intended for expressing your interest in_writing a new tutorial. For general questions or requests, please consider posting to https://stackoverflow.com/questions/tagged/google-earth-engine or https://groups.google.com/g/google-earth-engine-developers. Thanks!
