### ISSUE TITLE
[Tutorial proposal] Anomalies time series analysis of soil moisture and precipitation over a river basin

### ISSUE THREAD

**Issue by nasa-gsfc-soilmoisture** [google/earthengine-community#648]
**What is the objective of the proposed tutorial?**
This script uses NASA-USDA Enhanced SMAP products and GPM IMERG Final Product to extract soil moisture and precipitation information for identifying prolonged drought in a river basin.

**What is the scope of the proposed tutorial?**
We demonstrates the value of NASA's Earth observation in detecting prolonged droughts over the Mosul River basin in the Middle East where in-situ measurements are not available or are inaccessible. We simply used anomalies of soil moisture (surface and sursurface) as well as precipitation to highlight drought periods during 2020-2021 where negative anomalies  were observed persistently for months. This tutorial presents a simple yet effective method for analyzing water budget dynamics in areas with limited ground data by using Earth observation data in Google Earth Engine.

**Please provide an outline of the structure of the proposed tutorial?**
1. Importing Mosul river basin boundary
2. Importing soil moisture and precipitation datasets
3. Processing suface soil moisture datasets
4. Processing subsurface soil moisture datasets
5. Processing precipitation datasets
6. Plot anomalies time series anomalies for both soil moisture and precipitation
7. Remarks

**In what format will you be submitting the tutorial?**
[Markdown](https://guides.github.com/features/mastering-markdown/)

This request will be reviewed by the Earth Engine community maintainers, who
will reply on this issue tracker with any questions or suggestions. Once
approved, this issue will be assigned to you and you can begin work on the
tutorial following instructions in
[Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write).
When creating your Pull Request, enter "Closes #issueno" in the description of
your Pull Request to link the tutorial to this issue.

**Comment by jdbcode** [comment]
I love that you are doing a small, practical example that others can potentially use for their own regions of interest.

Thanks for the details – everything looks good at this point.

Please proceed with completing the tutorial following the [markdown instructions](https://developers.google.com/earth-engine/tutorials/community/write#markdown-quick-start). You can see other [markdown tutorial examples](https://github.com/google/earthengine-community/tree/master/tutorials) to get a better sense for folder and file names.

Let us know here if you have any questions. We'll look forward to seeing your pull request!

**Comment by nasa-gsfc-soilmoisture** [comment]
Thank you for your approval. We have created a pull request. Please let me know if you have any questions

**Comment by nasa-gsfc-soilmoisture** [comment]
Hi Justin, 

Just a friendly remind on the status of this tutorial.  Have you had a chance to check our submitted scripts?

Thanks,
Hung

**Comment by jdbcode** [comment]
Hi Hung, there are two other pull requests ahead of yours. We're getting through them, it's just taking time, apologies for the delay.

**Comment by jdbcode** [comment]
Hung, there are a few problems I see before looking at the tutorial.

1. The **tutorial markdown file needs a folder**

Looking at https://github.com/nasa-gsfc-soilmoisture/earthengine-community/tree/050ec3be7caf326d5d1c702ebd09da07b81befb4/tutorials

![image](https://user-images.githubusercontent.com/9044197/228895172-0be79ee0-02a7-4a5c-9b81-c845f9264ea2.png)

2. **The name of the tutorial folder (current file name) is too long**, please shorten (use examples from https://github.com/nasa-gsfc-soilmoisture/earthengine-community/tree/050ec3be7caf326d5d1c702ebd09da07b81befb4/tutorials as a guide for length). The folder name and the title of the tutorial in the markdown header do not need to match.

https://github.com/nasa-gsfc-soilmoisture/earthengine-community/blob/050ec3be7caf326d5d1c702ebd09da07b81befb4/tutorials/anomalies-time-series-analysis-of-soil-moisture-and-precipitation-over-a-river-basin

3. The markdown **tutorial file name needs to be "index.md"**

You can **fix issues 1-3 by editing the file in the GitHub site**:

- go to the file and click the pencil button to edit: https://github.com/nasa-gsfc-soilmoisture/earthengine-community/blob/050ec3be7caf326d5d1c702ebd09da07b81befb4/tutorials/anomalies-time-series-analysis-of-soil-moisture-and-precipitation-over-a-river-basin

![image](https://user-images.githubusercontent.com/9044197/228896684-be0350ae-3718-4fb7-b685-220a9e4f1690.png)

- follow these steps to add a folder and rename the file: https://github.blog/2013-03-15-moving-and-renaming-files-on-github/


4. **I don't see the pull request**. I think you've only committed the change to a branch of your fork. You'll need to hit the green "Create Pull Request" button on [this page](https://github.com/google/earthengine-community/compare/master...nasa-gsfc-soilmoisture:earthengine-community:nasa-gsfc-soilmoisture-patch-1) and follow the prompts.

![image](https://user-images.githubusercontent.com/9044197/228897462-cfe88b68-fe80-4f3f-870d-bcc76c3a700f.png)

**Comment by nasa-gsfc-soilmoisture** [comment]
Thanks, Justin for a detailed instruction! I have followed it. Please let me know if you have any further questions.

Hung

**Comment by jdbcode** [comment]
#651 closes the issue
