### ISSUE TITLE
[Tutorial proposal] Introduction to SMAP

### ISSUE THREAD

**Issue by purplekrayon** [google/earthengine-community#652]
**What is the objective of the proposed tutorial?**
Learn how to visualize and analyze SMAP data in GEE.

**What is the scope of the proposed tutorial?**
The thematic focus is learning about the SMAP instrument for applications related to water resources management. Users will learn how import, visualize, and analyze a time series SMAP soil moisture products.

**Please provide an outline of the structure of the proposed tutorial?**
1. SMAP mission
  a. Mission objective
  b. Instrument description
  c. Passive Microwave Concepts
  d. What does SMAP measure?
2. SMAP products in GEE
   a. SMAP level 3
   b. SMAP level 4
   c. SMAP NASA/USDA enhanced
3.  Visualizing SMAP
4.  Plotting a time series of daily soil moisture
5.  Calculating weekly soil moisture anomalies
6.  Advanced tutorial: Links to [https://github.com/google/earthengine-community/issues/648#issuecomment-1474516457]

**In what format will you be submitting the tutorial?**
Select one: Markdown

This request will be reviewed by the Earth Engine community maintainers, who
will reply on this issue tracker with any questions or suggestions. Once
approved, this issue will be assigned to you and you can begin work on the
tutorial following instructions in
[Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write).
When creating your Pull Request, enter "Closes #issueno" in the description of
your Pull Request to link the tutorial to this issue.

**Comment by TechandEco** [comment]
Congratulations, your community tutorial proposal has been accepted! To get
started writing a new tutorial, please follow
[these instructions](https://developers.google.com/earth-engine/tutorials/community/write).
Looking forward to receiving your contributions!

**Comment by purplekrayon** [comment]
Thank you! I have most of the tutorial written already. I'm holding a live training for the US forest service on April 25th. When is the latest I can submit my tutorial for your review so it can be posted by the training date?

**Comment by TechandEco** [comment]
Hello, please submit it as soon as you can, and we will do our best. We cannot guarantee the specific date however, but will do our best as well.

**Comment by TechandEco** [comment]
Hello, please note, in order to speed up the approval process as well, you will need to include a small thumbnail 600px wide by 340px high in your pull request, you will need to call it thumbnail.png

For context this is to display a small image of your tutorial like the rest https://developers.google.com/earth-engine/tutorials/community/explore

Cheers!

**Comment by purplekrayon** [comment]
Thanks! I added the png to the pull request.

**Comment by jdbcode** [comment]
#654 closes the issue
