### ISSUE TITLE
[Tutorial proposal] INTRODUÇÃO AO GOOGLE EARTH ENGINE

### ISSUE THREAD

**Issue by wesleymarchi** [google/earthengine-community#672]
**What is the objective of the proposed tutorial?**
In a first step, understand the Code Editor and explain the basics of JavaScript to use in GEE. Then, apply the API features and lastly, build an application..

**What is the scope of the proposed tutorial?**
Forest, water resources and specific geographic - Iguassu Falls - Paraná, Brazil..

**Please provide an outline of the structure of the proposed tutorial?**
1. Interface
  a. Code Editor
2. Introduction to JavaScript
  a. Data Types in JavaScript
  b. Constraints on naming variables
  c. Accessing and Changing an Array
  d. Expressions and Operators
  e. Conditionals, Condition Operators and Logical Operators
  f. Switch Structure
  g. Loops
  h. Functions
  i. Objects
3. Earth Engine Objects
  a. Strings
  b. Numbers
  c. Lists
  d. Casting
  e. Dictionary
  f. Dates
4. Hands-on: Viewing Images and Image Bands
  a. View Customization
  b. Adding Colors
5. Hands-on: Calculations
  a. Map Algebra
  b. Image Statistics
6. Image Collections
  a. Filtering
  b. Composition with reducers
7. App with GEE

**In what format will you be submitting the tutorial?**
[Markdown](https://guides.github.com/features/mastering-markdown/)

This request will be reviewed by the Earth Engine community maintainers, who
will reply on this issue tracker with any questions or suggestions. Once
approved, this issue will be assigned to you and you can begin work on the
tutorial following instructions in
[Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write).
When creating your Pull Request, enter "Closes #issueno" in the description of
your Pull Request to link the tutorial to this issue.

**Comment by wesleymarchi** [comment]
Hello how are you?
The idea would be in Portuguese - BR, because here in Brazil this technology is still little used and needs greater dissemination.

Many people from academia and the market would like to learn.

**Comment by gino-m** [comment]
Hi @wesleymarchi, so sorry for the delay.  We'd love to receive and review your tutorial. You can find instructions [here](https://developers.google.com/earth-engine/tutorials/community/write) on how to get started. Let us know if you have any questions!

**Comment by murillocosta** [comment]
@wesleymarchi Hey, man! how are you?
I'd love to help you with this. 
If you need anything, I'll be happy to help

**Comment by wesleymarchi** [comment]
Good afternoon, how are you?

Sorry for the delay in responding, there was a lot of demand for postgraduate studies. I will start this demand.

Thank you!

**Comment by jdbcode** [comment]
Hello, is there anything we can do to help move the process along? If it is something that you don't think you'll be able to get to, it is okay to close the issue as well.
