### ISSUE TITLE
[Community Tutorials] Users that are not logged into GitHub see error page after clicking 'fork' link in docs

### ISSUE THREAD

**Issue by gino-m** [google/earthengine-community#70]

**Comment by Bbowen1978** [comment]
-label:bug

**Comment by Bbowen1978** [comment]
-label:bug

**Comment by gino-m** [comment]
Sign in is first step in instructions in https://developers.google.com/earth-engine/tutorials/community/write#writing_and_submitting_a_tutorial, so considering working as intended.
