### ISSUE TITLE
[Tutorial proposal] How to authenticate GEE PYTHON API?

### ISSUE THREAD

**Issue by scanhanga** [google/earthengine-community#733]
Hi all.
I am trying to use the CoastSat toolkit, to retrieve the time series of coast line. One of the pre-requirement, is to activate the GEE. 

I am struggling here to activate the GEE Python API, becouse when I try to authenticate the GEE by using ee.Authenticate(), it open an web page which is written the following: 

![image](https://github.com/google/earthengine-community/assets/72568382/1b3329be-bb58-446d-af41-59eaacf5c991)

or then 

The version of the app you're using doesn't include the latest security features to keep you protected. Please make sure to download from a trusted source and update to the latest, most secure version.
Se for programador de Google Earth Engine Authenticator, veja os [detalhes do erro](https://accounts.google.com/).
Erro 400: invalid_request

I tried to solve it by updating the GEE, by using conda update command, as follow, 

conda update -c conda-forge earthengine-api;

and this error appeared 

![image](https://github.com/google/earthengine-community/assets/72568382/8fa8c3f4-edb1-4c0b-98d6-d1febee81fba)

and still is not working.. Can one assist me on this?
I would Really appreciate.
And Thanks in advance

**Comment by gino-m** [comment]
Hi @scanhanga, this issue tracker is intended for offering to write new content for the community tutorials section of our documentation site. Check out this page for several ways of getting help with Earth Engine:

https://developers.google.com/earth-engine/help

That said, it appears you have a typo into your `import` statement (`impoert` vs `import`). Hope that helps. Please be sure to follow up via one of the channels in the linked page for further assistance.
