### ISSUE TITLE
Error with: Uploading image tiles as a single asset using a manifest

### ISSUE THREAD

**Issue by mbayad33** [google/earthengine-community#775]
Hello, 
I have an issue when running this script. 
https://github.com/google/earthengine-community/blob/master/guides/linked/Uploading_image_tiles_as_a_single_asset_using_a_manifest.ipynb

I get the following error: 
No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
Encountered 403 Forbidden with reason "PERMISSION_DENIED"
Google Earth Engine API has not been used in project 522309567947 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/earthengine.googleapis.com/overview?project=522309567947 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Howeve, I have no project with that number.
and I have access permissions to the ee-project where my asset is located.
Can anyone help me identify what is the issue here? 

Thank you

**Comment by jdbcode** [comment]
What cell throws the error?
If it is the cell with `ee.Initialize(project='my-project')`, make sure you specify a cloud project that is Earth Engine enabled and one that you have permission to use for compute (like if your the project owner or have [writer or admin roles](roles/earthengine.writer)). Typically the at error message means you did not specify a project (that error message should become more helpful in the next release of the API, BTW).

**Comment by mbayad33** [comment]
Yes, it is ee.Initialize(project='my-project') that return the error, although I have all the necessary permissions to use the projects (owner role). 
This code runs fine in jupyter notebook in local computer, but in colab it returns the "permission denied" error.

**Comment by jdbcode** [comment]
I see - yes there is an issue here. We'll need to redo the auth / init steps in this example because of API [changes](https://developers.google.com/earth-engine/changelog#python_api_v01383) introduced in version 0.1.383.

I'll repost the notebook and let you know when it is ready.

Thanks for reporting the issue!

**Comment by jdbcode** [comment]
Additionally, the demo image tiles are no longer valid. Need to find new tiles to use for the demo.

Not valid:

urls = [
  'http://data.ess.tsinghua.edu.cn/data/fromglc10_2017v01/fromglc10v01_36_-120.tif',
  'http://data.ess.tsinghua.edu.cn/data/fromglc10_2017v01/fromglc10v01_36_-122.tif',
  'http://data.ess.tsinghua.edu.cn/data/fromglc10_2017v01/fromglc10v01_36_-124.tif',
  'http://data.ess.tsinghua.edu.cn/data/fromglc10_2017v01/fromglc10v01_38_-120.tif',
  'http://data.ess.tsinghua.edu.cn/data/fromglc10_2017v01/fromglc10v01_38_-122.tif',
  'http://data.ess.tsinghua.edu.cn/data/fromglc10_2017v01/fromglc10v01_38_-124.tif'
]

Providing site is unavailable: http://data.ess.tsinghua.edu.cn/fromglc10_2017v01.html

**Comment by jdbcode** [comment]
@mbayad33 thanks again for raising this issue.

The notebook has been updated with new authentication/initialization instructions and valid image tiles.

Please see the new notebook here: https://github.com/google/earthengine-community/blob/master/guides/linked/Uploading_image_tiles_as_a_single_asset_using_a_manifest.ipynb

I've tested the notebook with success, so will close the issue, please reopen if it does not work for you.
