### ISSUE TITLE
[Tutorial proposal] Species Distribution Modeling Using Google Earth Engine

### ISSUE THREAD

**Issue by osgeokr** [google/earthengine-community#776]
**What is the objective of the proposed tutorial?**
Species Distribution Modeling (SDM) is a model that uses computer algorithms to predict the distribution of species across geographic spatiotemporal dimensions. The tutorial I propose will introduce how to implement SDM using Google Earth Engine (GEE). I plan to write this content through the Python API, and it is already preliminarily written in the following repository: [GitHub](https://github.com/osgeokr/pySDM-geemap/). I am confident this tutorial will be useful for environmentalists or ecologists who want to map potential habitats or habitat suitability through GEE.

**What is the scope of the proposed tutorial?**
It can be utilized in various fields, focusing on Ecology.

**Please provide an outline of the structure of the proposed tutorial?**
Section 1: What is Species Distribution Modeling?
 a. Subsection 1a: Definition of SDM
 b. Subsection 1b: Workflow of SDM
 c. Subsection 1c: Introduction to Pitta nympha (Endangered Bird Species)
Section 2: GEE-Based SDM: A Case Study on Pitta Nympha Analysis
a. Subsection 2a: Collection and Processing of Species Occurrence Data
b. Subsection 2b: Defining the Area of Interest
c. Subsection 2c: Adding Predictive Variables
d. Subsection 2d: Generation of Presence-Absence Data
e. Subsection 2e: SDM Model Prediction
f. Subsection 2f: Variable Importance and Accuracy Assessment

**In what format will you be submitting the tutorial?**
Select one: [Markdown](https://guides.github.com/features/mastering-markdown/)
or [Colab](https://research.google.com/colaboratory/faq.html)
I will submit it in Colab format.

This request will be reviewed by the Earth Engine community maintainers, who
will reply on this issue tracker with any questions or suggestions. Once
approved, this issue will be assigned to you and you can begin work on the
tutorial following instructions in
[Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write).
When creating your Pull Request, enter "Closes #issueno" in the description of
your Pull Request to link the tutorial to this issue.

**Comment by jdbcode** [comment]
The tutorial looks great - thanks for proposing!

I took a really quick look at the existing notebook. I think it'll all be fine. Just a couple suggestions:

- Make sure that it will work in Colab (I see that it is loading and writing to local files - make sure that everything a person needs, can be fetched via download from the repo - like include pitta_nympha_data.gpkg in the tutorial folder and download it in the notebook.)
- Include a couple sentences to each section to explain with a little more detail about what the code is doing - inputs, process, expected output - and any important interpretation of the result or method if not obvious.
- Make sure that people are initializing Earth Engine with a cloud project - in the notebook you can use `ee.Initialize(project='your-project')` as a placeholder.

Please proceed with the next steps and let us know if you have any questions or run into any issues.

Best,
Justin

**Comment by jdbcode** [comment]
#789 closes this issue
