### ISSUE TITLE
Tutorial Request: <title>trading bot evolving code

### ISSUE THREAD

**Issue by piizi12** [google/earthengine-community#786]
I would like to get instructions on how to make profitabile bot for trading purposes that is lerning along with the market changes.

Technical Level
beginner | intermediate | advanced

Length

short (< 250 words) | medium (250-500 words) | long (1000 words 

Please help dont know how to code but I can follow instructions or premade templates

**Comment by gino-m** [comment]
Hi @piizi12, I think you may have posted your request to the wrong project. Closing this issue.
