### ISSUE TITLE
Issue with Cloud Masking with s2cloudless

### ISSUE THREAD

**Issue by danielm09** [google/earthengine-community#803]
Hi.

There is some issue with the cloud masking process described in this [tutorial](https://developers.google.com/earth-engine/tutorials/community/sentinel-2-s2cloudless).
I still can't pin point what is the exact cause, but the effect is that the masking is not working properly - it seems that all pixels are being masked.
When executing this tutorial on [colab](https://colab.research.google.com/github/google/earthengine-community/blob/master/tutorials/sentinel-2-s2cloudless/index.ipynb), we cannot see the cloud mask and the cloud free composite generated in the last cell displayed on the map.

Upon running
`s2_sr_cld_col.map(add_cld_shdw_mask).map(apply_cld_shdw_mask).getRegion(geometry=AOI, scale=10).getInfo()` we get as a result:

[['id',
  'longitude',
  'latitude',
  'time',
  'B1',
  'B2',
  'B3',
  'B4',
  'B5',
  'B6',
  'B7',
  'B8',
  'B8A',
  'B9',
  'B11',
  'B12'],
 ['20200601T185919_20200601T190551_T10TER',
  -122.26901958504497,
  45.701026511589156,
  1591038717370,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None],
 ['20200619T190921_20200619T191722_T10TER',
  -122.26901958504497,
  45.701026511589156,
  1592594517900,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None],
and so on...]

Indicating that maybe the function is masking all pixels somehow.

Everything was working fine a few days ago.

I wonder if there is something wrong with the `COPERNICUS/S2_CLOUD_PROBABILITY` collection.

**Comment by jdbcode** [comment]
Thanks, Daniel! There are similar issues showing up in other use cases/demos where display tiles are incorrectly masked. I think it is not with the dataset. We're looking into it.

**Comment by jdbcode** [comment]
The notebook/operation is working as expected again after a server-side roll back. New tests should help catch these issues.

**Comment by danielm09** [comment]
Thanks, Justin.

I can confirm it is working fine here.
