### ISSUE TITLE
LGTM. Just a nitpick, for arithmetic variables we usually use the following form:

### ISSUE THREAD

**Issue by ibrahimkhled** [google/earthengine-community#869]
LGTM. Just a nitpick, for arithmetic variables we usually use the following form:
```suggestion
(( VERBATIM_OCCURRENCES == 2 )) || assertFail "Incorrect number of verbatim items in assembly."
```

_Originally posted by @r0qs in https://github.com/ethereum/solidity/pull/14649#discussion_r1385911220_

**Comment by jdbcode** [comment]
Unrelated to google/earthengine-community. Closing.
