### ISSUE TITLE
Initialize

### ISSUE THREAD

**Issue by iqbalhabibie1206** [google/earthengine-community#870]
I am trying to initialize after installing earth engine api in Google Colab. The steps is:

# Instalasi library yang diperlukan
!pip install earthengine-api

# Mengimpor library
import ee
import time

# Import Library Earth Engine
import ee
print(ee.__version__)

ee.Authenticate()

# Mengaktifkan GEE pada Google Colab
ee.Initialize() 

But I have an error:

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "PERMISSION_DENIED"
---------------------------------------------------------------------------
EEException                               Traceback (most recent call last)
[<ipython-input-3-3259c7bed695>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 # Mengaktifkan GEE pada Google Colab
----> 6 ee.Initialize()

1 frames
[/usr/local/lib/python3.10/dist-packages/ee/__init__.py](https://localhost:8080/#) in Initialize(credentials, url, cloud_api_key, http_transport, project)
    179     matches = re.search(api_err, str(e))
    180     if (adc_err in str(e)) or (matches and oauth.is_sdk_project(matches[1])):
--> 181       raise EEException(NO_PROJECT_EXCEPTION) from None
    182     raise e
    183   Array.initialize()

EEException: ee.Initialize: no project found. Call with project= or see http://goo.gle/ee-auth.

Any suggestion? Thanks.

**Comment by jdbcode** [comment]
You need to initialize with a Cloud project. 

`ee.Initialize(project='YOUR-CLOUD-PROJECT-ID')`

See the [EE Python Quickstart](https://developers.google.com/earth-engine/guides/quickstart_python) for a full working example and instructions for getting a Cloud project, if you don't have one.

In the future, please post questions like this to the [Earth Engine Developer Forum](https://developers.google.com/earth-engine/help#earth_engine_developer_forum).

**Comment by iqbalhabibie1206** [comment]
Yes i try this:ee.Initialize(project='YOUR-CLOUD-PROJECT-ID') by changing
'YOUR-CLOUD-PROJECT-ID' into users/userID so the initialize like
ee.Initialize(project='users/iqbal')but there is some error like before.
Any suggestion?

Best regards
Muhammad Iqbal

**Comment by jdbcode** [comment]
`users/iqbal` is not a Cloud project. Please register a cloud project: https://code.earthengine.google.com/register

**Comment by iqbalhabibie1206** [comment]
Ok thanks. So the other one. Thank you for your help. 🙏🏻
